// @generated by protoc-gen-es v1.10.0
// @generated from file protobuf/spotify/main.proto (package com.smile.spotify.model, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message com.smile.spotify.model.BootstrapResponse
 */
export const BootstrapResponse = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.BootstrapResponse",
  () => [
    { no: 2, name: "ucsResponseV0", kind: "message", T: UcsResponseWrapperV0, oneof: "ucsResponse" },
    { no: 3, name: "trialsFacadeResponseV1", kind: "message", T: TrialsFacadeResponseWrapperV1, oneof: "ucsResponse" },
  ],
);

/**
 * @generated from message com.smile.spotify.model.UcsResponseWrapperV0
 */
export const UcsResponseWrapperV0 = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.UcsResponseWrapperV0",
  () => [
    { no: 1, name: "success", kind: "message", T: UcsResponseWrapperSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: UcsResponseWrapperError, oneof: "result" },
  ],
);

/**
 * @generated from message com.smile.spotify.model.UcsResponseWrapperSuccess
 */
export const UcsResponseWrapperSuccess = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.UcsResponseWrapperSuccess",
  () => [
    { no: 1, name: "customization", kind: "message", T: UcsResponseWrapper },
  ],
);

/**
 * @generated from message com.smile.spotify.model.UcsResponseWrapperError
 */
export const UcsResponseWrapperError = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.UcsResponseWrapperError",
  () => [
    { no: 1, name: "errorCode", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "logId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.TrialsFacadeResponseWrapperV1
 */
export const TrialsFacadeResponseWrapperV1 = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.TrialsFacadeResponseWrapperV1",
  () => [
    { no: 1, name: "success", kind: "message", T: TrialsFacadeResponseWrapperSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: TrialsFacadeResponseWrapperError, oneof: "result" },
  ],
);

/**
 * @generated from message com.smile.spotify.model.TrialsFacadeResponseWrapperSuccess
 */
export const TrialsFacadeResponseWrapperSuccess = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.TrialsFacadeResponseWrapperSuccess",
  () => [
    { no: 1, name: "field1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.TrialsFacadeResponseWrapperError
 */
export const TrialsFacadeResponseWrapperError = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.TrialsFacadeResponseWrapperError",
  () => [
    { no: 1, name: "errorCode", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "logId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.UcsResponseWrapper
 */
export const UcsResponseWrapper = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.UcsResponseWrapper",
  () => [
    { no: 1, name: "success", kind: "message", T: UcsResponse, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: Error, oneof: "result" },
  ],
);

/**
 * @generated from message com.smile.spotify.model.UcsResponse
 */
export const UcsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.UcsResponse",
  () => [
    { no: 1, name: "resolveSuccess", kind: "message", T: ResolveResponse, oneof: "resolveResult" },
    { no: 2, name: "resolveError", kind: "message", T: Error, oneof: "resolveResult" },
    { no: 3, name: "accountAttributesSuccess", kind: "message", T: AccountAttributesResponse, oneof: "accountAttributesResult" },
    { no: 4, name: "accountAttributesError", kind: "message", T: Error, oneof: "accountAttributesResult" },
    { no: 5, name: "fetchTimeMillis", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.ResolveResponse
 */
export const ResolveResponse = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.ResolveResponse",
  () => [
    { no: 1, name: "configuration", kind: "message", T: Configuration },
  ],
);

/**
 * @generated from message com.smile.spotify.model.Configuration
 */
export const Configuration = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.Configuration",
  () => [
    { no: 1, name: "configurationAssignmentId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "fetchTimeMillis", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "assignedValues", kind: "message", T: AssignedValue, repeated: true },
    { no: 4, name: "policySnapshotId", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.AssignedValue
 */
export const AssignedValue = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.AssignedValue",
  () => [
    { no: 1, name: "propertyId", kind: "message", T: Identifier },
    { no: 2, name: "metadata", kind: "message", T: Metadata },
    { no: 3, name: "boolValue", kind: "message", T: BoolValue, oneof: "structuredValue" },
    { no: 4, name: "intValue", kind: "message", T: IntValue, oneof: "structuredValue" },
    { no: 5, name: "enumValue", kind: "message", T: EnumValue, oneof: "structuredValue" },
  ],
);

/**
 * @generated from message com.smile.spotify.model.Identifier
 */
export const Identifier = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.Identifier",
  () => [
    { no: 1, name: "scope", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.Metadata
 */
export const Metadata = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.Metadata",
  () => [
    { no: 1, name: "policyId", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "externalRealm", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "externalRealmId", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.BoolValue
 */
export const BoolValue = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.BoolValue",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.EnumValue
 */
export const EnumValue = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.EnumValue",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.IntValue
 */
export const IntValue = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.IntValue",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message com.smile.spotify.model.AccountAttributesResponse
 */
export const AccountAttributesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.AccountAttributesResponse",
  () => [
    { no: 1, name: "accountAttributes", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: AccountAttribute} },
  ],
);

/**
 * @generated from message com.smile.spotify.model.AccountAttribute
 */
export const AccountAttribute = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.AccountAttribute",
  () => [
    { no: 2, name: "boolValue", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "value" },
    { no: 3, name: "longValue", kind: "scalar", T: 3 /* ScalarType.INT64 */, oneof: "value" },
    { no: 4, name: "stringValue", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "value" },
  ],
);

/**
 * @generated from message com.smile.spotify.model.Error
 */
export const Error = /*@__PURE__*/ proto3.makeMessageType(
  "com.smile.spotify.model.Error",
  () => [
    { no: 1, name: "errorCode", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "errorMessage", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

