#!name= BlockADS
#!desc=ADS VN
[Rule]
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,eclick.vn,REJECT
DOMAIN-SUFFIX,googleadservices.com,REJECT
DOMAIN-SUFFIX,pubmatic.com,REJECT
DOMAIN-SUFFIX,admicro.vn,REJECT
DOMAIN,advertising.amazon.com,REJECT

[URL Rewrite]
^https?:\/\/[\w-]+\.googlevideo\.com\/.+(&oad|ctier) - reject
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads - reject
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) - reject
^https?:\/\/\s.youtube.com/api/stats/qoe?.*adformat= - reject
[MITM]
hostname = %APPENP% www.youtube.com,s.youtube.com,googlevideo.com
