# Author: Hoangsvn
# Email: i36nxhvn@icloud.com
# Title: AD-Block Vn
# Last modified: 15/09/2025, 23:08:08 UTC+7
# Blocked: 1,960 host
# Version: 2509151608
# Only include advertisers in Vietnam

#!name=AD-Block Vn
#!desc=build:9/15/2025, 4:08:08 PM
#!url=https://raw.githubusercontent.com/hoangsvn/hoangsvn/main/module/adblockvn.module

[Rule]
# [10gb.vn]
DOMAIN-SUFFIX,tracking.10gb.vn,REJECT
# [123c.vn]
DOMAIN-SUFFIX,hit.123c.vn,REJECT
DOMAIN-SUFFIX,stats.123c.vn,REJECT
DOMAIN-SUFFIX,trk.123c.vn,REJECT
DOMAIN-SUFFIX,trk.staging.123c.vn,REJECT
# [12signup.com]
DOMAIN-SUFFIX,12signup.com,REJECT
DOMAIN-SUFFIX,www.12signup.com,REJECT
# [1cdn.vn]
DOMAIN-SUFFIX,logs.1cdn.vn,REJECT
# [1thegioi.vn]
DOMAIN-SUFFIX,1thegioi.vn,REJECT
DOMAIN-SUFFIX,ads.1thegioi.vn,REJECT
# [1vn.app]
DOMAIN-SUFFIX,log.1vn.app,REJECT
# [200lab.io]
DOMAIN-SUFFIX,mautic.200lab.io,REJECT
# [247post.vn]
DOMAIN-SUFFIX,log.247post.vn,REJECT
# [24hstatic.com]
DOMAIN-SUFFIX,24h-ad.24hstatic.com,REJECT
DOMAIN-SUFFIX,24h-ipad-ad.24hstatic.com,REJECT
DOMAIN-SUFFIX,24hstatic.com,REJECT
DOMAIN-SUFFIX,ad-us.24hstatic.com,REJECT
DOMAIN-SUFFIX,eva-ad.24hstatic.com,REJECT
DOMAIN-SUFFIX,nv-ad.24hstatic.com,REJECT
# [568play.vn]
DOMAIN-SUFFIX,568play.vn,REJECT
DOMAIN-SUFFIX,ads.568play.vn,REJECT
# [5giay.vn]
DOMAIN-SUFFIX,banner.5giay.vn,REJECT
DOMAIN-SUFFIX,qc.5giay.vn,REJECT
# [6895588.com]
DOMAIN-SUFFIX,ak9.6895588.com,REJECT
# [6svn.com]
DOMAIN-SUFFIX,6svn.com,REJECT
DOMAIN-SUFFIX,ads.6svn.com,REJECT
# [aanetwork.vn]
DOMAIN-SUFFIX,aanetwork.vn,REJECT
DOMAIN-SUFFIX,cdn.aanetwork.vn,REJECT
DOMAIN-SUFFIX,imgs2.aanetwork.vn,REJECT
DOMAIN-SUFFIX,pub.aanetwork.vn,REJECT
# [accesstrade.vn]
DOMAIN-SUFFIX,accesstrade.vn,REJECT
DOMAIN-SUFFIX,ad.accesstrade.vn,REJECT
DOMAIN-SUFFIX,partner.accesstrade.vn,REJECT
DOMAIN-SUFFIX,service-api.accesstrade.vn,REJECT
DOMAIN-SUFFIX,static.accesstrade.vn,REJECT
DOMAIN-SUFFIX,track.accesstrade.vn,REJECT
# [adasiaholdings.com]
DOMAIN-SUFFIX,adasiaholdings.com,REJECT
DOMAIN-SUFFIX,adnetwork.adasiaholdings.com,REJECT
DOMAIN-SUFFIX,advertisers.adasiaholdings.com,REJECT
DOMAIN-SUFFIX,apm.adasiaholdings.com,REJECT
DOMAIN-SUFFIX,media.adasiaholdings.com,REJECT
DOMAIN-SUFFIX,pixel.adasiaholdings.com,REJECT
DOMAIN-SUFFIX,publishers.adasiaholdings.com,REJECT
DOMAIN-SUFFIX,www.adasiaholdings.com,REJECT
# [adbro.me]
DOMAIN-SUFFIX,adbro.me,REJECT
DOMAIN-SUFFIX,api.adbro.me,REJECT
DOMAIN-SUFFIX,apis.adbro.me,REJECT
DOMAIN-SUFFIX,cdn.adbro.me,REJECT
DOMAIN-SUFFIX,portal.adbro.me,REJECT
DOMAIN-SUFFIX,tag.adbro.me,REJECT
# [adchoice.com]
DOMAIN-SUFFIX,adchoice.com,REJECT
# [adcolony.com]
DOMAIN-SUFFIX,adcolony.com,REJECT
# [adconnect.vn]
DOMAIN-SUFFIX,adconnect.vn,REJECT
DOMAIN-SUFFIX,static.adconnect.vn,REJECT
# [adflex.vn]
DOMAIN-SUFFIX,adflex.vn,REJECT
DOMAIN-SUFFIX,ads.adflex.vn,REJECT
DOMAIN-SUFFIX,adv.adflex.vn,REJECT
DOMAIN-SUFFIX,aff.adflex.vn,REJECT
DOMAIN-SUFFIX,ap.adflex.vn,REJECT
DOMAIN-SUFFIX,apk.adflex.vn,REJECT
DOMAIN-SUFFIX,cdn.adflex.vn,REJECT
DOMAIN-SUFFIX,cdn2.adflex.vn,REJECT
DOMAIN-SUFFIX,cloudfront.adflex.vn,REJECT
DOMAIN-SUFFIX,cpi.adflex.vn,REJECT
DOMAIN-SUFFIX,cpo.adflex.vn,REJECT
DOMAIN-SUFFIX,dev.adflex.vn,REJECT
DOMAIN-SUFFIX,dn.adflex.vn,REJECT
DOMAIN-SUFFIX,ecm.adflex.vn,REJECT
DOMAIN-SUFFIX,ecn.adflex.vn,REJECT
DOMAIN-SUFFIX,image-static.adflex.vn,REJECT
DOMAIN-SUFFIX,image.static.adflex.vn,REJECT
DOMAIN-SUFFIX,image3.static.adflex.vn,REJECT
DOMAIN-SUFFIX,kiemtien.adflex.vn,REJECT
DOMAIN-SUFFIX,log.adflex.vn,REJECT
DOMAIN-SUFFIX,mediation.adflex.vn,REJECT
DOMAIN-SUFFIX,pi.adflex.vn,REJECT
DOMAIN-SUFFIX,po.adflex.vn,REJECT
DOMAIN-SUFFIX,pub.adflex.vn,REJECT
DOMAIN-SUFFIX,schemas.adflex.vn,REJECT
DOMAIN-SUFFIX,sdk.adflex.vn,REJECT
DOMAIN-SUFFIX,static2.adflex.vn,REJECT
DOMAIN-SUFFIX,tmp.adflex.vn,REJECT
DOMAIN-SUFFIX,track.adflex.vn,REJECT
DOMAIN-SUFFIX,tracking.adflex.vn,REJECT
DOMAIN-SUFFIX,update.adflex.vn,REJECT
DOMAIN-SUFFIX,v2.api.adflex.vn,REJECT
DOMAIN-SUFFIX,www.adflex.vn,REJECT
# [adfly.vn]
DOMAIN-SUFFIX,adfly.vn,REJECT
DOMAIN-SUFFIX,api.adfly.vn,REJECT
DOMAIN-SUFFIX,www.adfly.vn,REJECT
# [adlinknetwork.vn]
DOMAIN-SUFFIX,adlinknetwork.vn,REJECT
DOMAIN-SUFFIX,service.adlinknetwork.vn,REJECT
DOMAIN-SUFFIX,syndication.adlinknetwork.vn,REJECT
# [admatrix.vn]
DOMAIN-SUFFIX,admatrix.vn,REJECT
DOMAIN-SUFFIX,ads.admatrix.vn,REJECT
# [admicro.vn]
DOMAIN-SUFFIX,adi.admicro.vn,REJECT
DOMAIN-SUFFIX,admicro.vn,REJECT
DOMAIN-SUFFIX,adx.admicro.vn,REJECT
DOMAIN-SUFFIX,b.logging.admicro.vn,REJECT
DOMAIN-SUFFIX,beta.admicro.vn,REJECT
DOMAIN-SUFFIX,boxpr.admicro.vn,REJECT
DOMAIN-SUFFIX,brand.admicro.vn,REJECT
DOMAIN-SUFFIX,cmsanalytics.admicro.vn,REJECT
DOMAIN-SUFFIX,content-ml.admicro.vn,REJECT
DOMAIN-SUFFIX,corenlp.admicro.vn,REJECT
DOMAIN-SUFFIX,defaultdsp.admicro.vn,REJECT
DOMAIN-SUFFIX,demo.corenlp.admicro.vn,REJECT
DOMAIN-SUFFIX,dio.admicro.vn,REJECT
DOMAIN-SUFFIX,dl.logging.admicro.vn,REJECT
DOMAIN-SUFFIX,enterpriseapi.admicro.vn,REJECT
DOMAIN-SUFFIX,file.admicro.vn,REJECT
DOMAIN-SUFFIX,fingerprint.admicro.vn,REJECT
DOMAIN-SUFFIX,hd.logging.admicro.vn,REJECT
DOMAIN-SUFFIX,k.logging.admicro.vn,REJECT
DOMAIN-SUFFIX,lg.logging.admicro.vn,REJECT
DOMAIN-SUFFIX,lg1.logging.admicro.vn,REJECT
DOMAIN-SUFFIX,logging.admicro.vn,REJECT
DOMAIN-SUFFIX,marketingai.admicro.vn,REJECT
DOMAIN-SUFFIX,mb.logging.admicro.vn,REJECT
DOMAIN-SUFFIX,media1.admicro.vn,REJECT
DOMAIN-SUFFIX,notify-service.admicro.vn,REJECT
DOMAIN-SUFFIX,pio.admicro.vn,REJECT
DOMAIN-SUFFIX,pson.logging.admicro.vn,REJECT
DOMAIN-SUFFIX,rec.admicro.vn,REJECT
DOMAIN-SUFFIX,sspapi.admicro.vn,REJECT
DOMAIN-SUFFIX,static-cmsads.admicro.vn,REJECT
DOMAIN-SUFFIX,supply-sspapi.admicro.vn,REJECT
DOMAIN-SUFFIX,systracking.admicro.vn,REJECT
DOMAIN-SUFFIX,wcc.admicro.vn,REJECT
DOMAIN-SUFFIX,www.admicro.vn,REJECT
# [admob.com]
DOMAIN-SUFFIX,admob.com,REJECT
# [adop.asia]
DOMAIN-SUFFIX,adop.asia,REJECT
DOMAIN-SUFFIX,cdn.adop.asia,REJECT
DOMAIN-SUFFIX,media.adop.asia,REJECT
DOMAIN-SUFFIX,www.adop.asia,REJECT
# [adpia.vn]
DOMAIN-SUFFIX,ac.adpia.vn,REJECT
DOMAIN-SUFFIX,adpia.vn,REJECT
DOMAIN-SUFFIX,click.adpia.vn,REJECT
DOMAIN-SUFFIX,event.adpia.vn,REJECT
DOMAIN-SUFFIX,front.adpia.vn,REJECT
DOMAIN-SUFFIX,healcheck.adpia.vn,REJECT
DOMAIN-SUFFIX,img.adpia.vn,REJECT
DOMAIN-SUFFIX,s3.adpia.vn,REJECT
DOMAIN-SUFFIX,sendy.adpia.vn,REJECT
DOMAIN-SUFFIX,smartlink.adpia.vn,REJECT
DOMAIN-SUFFIX,uptime.adpia.vn,REJECT
DOMAIN-SUFFIX,www.adpia.vn,REJECT
# [adrealclick.com]
DOMAIN-SUFFIX,adrealclick.com,REJECT
DOMAIN-SUFFIX,stats.adrealclick.com,REJECT
DOMAIN-SUFFIX,www.adrealclick.com,REJECT
# [adshay.vn]
DOMAIN-SUFFIX,track.adshay.vn,REJECT
# [adsmogo.org]
DOMAIN-SUFFIX,adsmogo.org,REJECT
# [adsota.com]
DOMAIN-SUFFIX,adsota.com,REJECT
DOMAIN-SUFFIX,agency.adsota.com,REJECT
DOMAIN-SUFFIX,app.adsota.com,REJECT
DOMAIN-SUFFIX,highlandscoffee.adsota.com,REJECT
DOMAIN-SUFFIX,static.adsota.com,REJECT
DOMAIN-SUFFIX,track.adsota.com,REJECT
DOMAIN-SUFFIX,www.adsota.com,REJECT
# [adsparc.com]
DOMAIN-SUFFIX,adsparc.com,REJECT
DOMAIN-SUFFIX,play.adsparc.com,REJECT
DOMAIN-SUFFIX,prebid.adsparc.com,REJECT
DOMAIN-SUFFIX,publisher.adsparc.com,REJECT
DOMAIN-SUFFIX,pushad.adsparc.com,REJECT
DOMAIN-SUFFIX,video.adsparc.com,REJECT
DOMAIN-SUFFIX,www.adsparc.com,REJECT
# [adsparc.net]
DOMAIN-SUFFIX,adsmt1.adsparc.net,REJECT
DOMAIN-SUFFIX,adsparc.net,REJECT
DOMAIN-SUFFIX,adsuite.adsparc.net,REJECT
DOMAIN-SUFFIX,adsvr.adsparc.net,REJECT
DOMAIN-SUFFIX,adsvr2.adsparc.net,REJECT
DOMAIN-SUFFIX,demo.adsparc.net,REJECT
DOMAIN-SUFFIX,hi-cdn.adsparc.net,REJECT
DOMAIN-SUFFIX,pb.adsparc.net,REJECT
DOMAIN-SUFFIX,pixel.adsparc.net,REJECT
DOMAIN-SUFFIX,www.adsparc.net,REJECT
# [adsplay.net]
DOMAIN-SUFFIX,admin.adsplay.net,REJECT
DOMAIN-SUFFIX,adsplay.net,REJECT
DOMAIN-SUFFIX,d.adsplay.net,REJECT
DOMAIN-SUFFIX,d1.adsplay.net,REJECT
DOMAIN-SUFFIX,d2.adsplay.net,REJECT
DOMAIN-SUFFIX,d3.adsplay.net,REJECT
DOMAIN-SUFFIX,d4.adsplay.net,REJECT
DOMAIN-SUFFIX,d5.adsplay.net,REJECT
DOMAIN-SUFFIX,d6.adsplay.net,REJECT
DOMAIN-SUFFIX,engineering.adsplay.net,REJECT
DOMAIN-SUFFIX,id.adsplay.net,REJECT
DOMAIN-SUFFIX,log.adsplay.net,REJECT
DOMAIN-SUFFIX,log1.adsplay.net,REJECT
DOMAIN-SUFFIX,log2.adsplay.net,REJECT
DOMAIN-SUFFIX,log3.adsplay.net,REJECT
DOMAIN-SUFFIX,log4.adsplay.net,REJECT
DOMAIN-SUFFIX,report.adsplay.net,REJECT
DOMAIN-SUFFIX,st.adsplay.net,REJECT
DOMAIN-SUFFIX,static.adsplay.net,REJECT
DOMAIN-SUFFIX,www.adsplay.net,REJECT
# [adsplus.vn]
DOMAIN-SUFFIX,adsplus.vn,REJECT
# [adsweb.vn]
DOMAIN-SUFFIX,adsweb.vn,REJECT
# [adtima.org]
DOMAIN-SUFFIX,adtima.org,REJECT
# [adtima.vn]
DOMAIN-SUFFIX,adtima.vn,REJECT
DOMAIN-SUFFIX,api.adtima.vn,REJECT
DOMAIN-SUFFIX,demo.adtima.vn,REJECT
DOMAIN-SUFFIX,gallery.adtima.vn,REJECT
DOMAIN-SUFFIX,ignite.adtima.vn,REJECT
DOMAIN-SUFFIX,manage.adtima.vn,REJECT
DOMAIN-SUFFIX,product.adtima.vn,REJECT
DOMAIN-SUFFIX,prp.adtima.vn,REJECT
DOMAIN-SUFFIX,static.adtima.vn,REJECT
DOMAIN-SUFFIX,stc.adtima.vn,REJECT
DOMAIN-SUFFIX,www.adtima.vn,REJECT
# [adtimaserver.vn]
DOMAIN-SUFFIX,adtimaserver.vn,REJECT
DOMAIN-SUFFIX,api.adtimaserver.vn,REJECT
DOMAIN-SUFFIX,log.adtimaserver.vn,REJECT
DOMAIN-SUFFIX,media.adtimaserver.vn,REJECT
DOMAIN-SUFFIX,media.org.adtimaserver.vn,REJECT
DOMAIN-SUFFIX,staging.api.adtimaserver.vn,REJECT
DOMAIN-SUFFIX,static.adtimaserver.vn,REJECT
DOMAIN-SUFFIX,static2.adtimaserver.vn,REJECT
DOMAIN-SUFFIX,stream.adtimaserver.vn,REJECT
DOMAIN-SUFFIX,stream.org.adtimaserver.vn,REJECT
DOMAIN-SUFFIX,web.api.adtimaserver.vn,REJECT
# [adtrafficquality.google]
DOMAIN-SUFFIX,adtrafficquality.google,REJECT
# [advertnative.com]
DOMAIN-SUFFIX,advertnative.com,REJECT
# [adx.vn]
DOMAIN-SUFFIX,adx.vn,REJECT
DOMAIN-SUFFIX,mon.adx.vn,REJECT
# [adxcontent.com]
DOMAIN-SUFFIX,adxcontent.com,REJECT
DOMAIN-SUFFIX,cdn.adxcontent.com,REJECT
# [afcdn.net]
DOMAIN-SUFFIX,afcdn.net,REJECT
# [affmates.com]
DOMAIN-SUFFIX,affmates.com,REJECT
DOMAIN-SUFFIX,api.affmates.com,REJECT
DOMAIN-SUFFIX,storage.affmates.com,REJECT
# [affordedseasick.com]
DOMAIN-SUFFIX,affordedseasick.com,REJECT
# [agiay.vn]
DOMAIN-SUFFIX,za.agiay.vn,REJECT
# [aiactiv.io]
DOMAIN-SUFFIX,adnetwork-adserver.aiactiv.io,REJECT
DOMAIN-SUFFIX,adnetwork-core-lb7.aiactiv.io,REJECT
DOMAIN-SUFFIX,adnetwork-core.aiactiv.io,REJECT
DOMAIN-SUFFIX,adnetwork-tracking-proxy.aiactiv.io,REJECT
DOMAIN-SUFFIX,aiactiv.io,REJECT
DOMAIN-SUFFIX,identify.aiactiv.io,REJECT
DOMAIN-SUFFIX,sdk-cdn.aiactiv.io,REJECT
DOMAIN-SUFFIX,static.aiactiv.io,REJECT
DOMAIN-SUFFIX,tag-cdn.aiactiv.io,REJECT
DOMAIN-SUFFIX,tags.aiactiv.io,REJECT
# [aiservice.vn]
DOMAIN-SUFFIX,aiservice.vn,REJECT
DOMAIN-SUFFIX,boxpr.aiservice.vn,REJECT
DOMAIN-SUFFIX,js.aiservice.vn,REJECT
DOMAIN-SUFFIX,lio.aiservice.vn,REJECT
DOMAIN-SUFFIX,nspapi.aiservice.vn,REJECT
DOMAIN-SUFFIX,rec.aiservice.vn,REJECT
# [aj1047.online]
DOMAIN-SUFFIX,aj1047.online,REJECT
# [aj2393.online]
DOMAIN-SUFFIX,aj2393.online,REJECT
# [akadigital.vn]
DOMAIN-SUFFIX,akadigital.vn,REJECT
DOMAIN-SUFFIX,delivery.akadigital.vn,REJECT
DOMAIN-SUFFIX,pub.akadigital.vn,REJECT
# [alexajstrack.com]
DOMAIN-SUFFIX,alexajstrack.com,REJECT
DOMAIN-SUFFIX,vn.alexajstrack.com,REJECT
# [almudestilths.com]
DOMAIN-SUFFIX,almudestilths.com,REJECT
# [alobacsi.vn]
DOMAIN-SUFFIX,ads.alobacsi.vn,REJECT
DOMAIN-SUFFIX,alobacsi.vn,REJECT
# [amazon.com]
DOMAIN-SUFFIX,advertising.amazon.com,REJECT
# [ambient-platform.com]
DOMAIN-SUFFIX,ambient-platform.com,REJECT
DOMAIN-SUFFIX,analytics.ambient-platform.com,REJECT
DOMAIN-SUFFIX,campaigns.ambient-platform.com,REJECT
DOMAIN-SUFFIX,cdn-media-m.ambient-platform.com,REJECT
DOMAIN-SUFFIX,cdn-media.ambient-platform.com,REJECT
DOMAIN-SUFFIX,cdn-media.m.ambient-platform.com,REJECT
DOMAIN-SUFFIX,cli.ambient-platform.com,REJECT
DOMAIN-SUFFIX,cli.m.ambient-platform.com,REJECT
DOMAIN-SUFFIX,conv.ambient-platform.com,REJECT
DOMAIN-SUFFIX,delivery-m.ambient-platform.com,REJECT
DOMAIN-SUFFIX,delivery.ambient-platform.com,REJECT
DOMAIN-SUFFIX,delivery.m.ambient-platform.com,REJECT
DOMAIN-SUFFIX,imp-m.ambient-platform.com,REJECT
DOMAIN-SUFFIX,imp.ambient-platform.com,REJECT
DOMAIN-SUFFIX,imp.m.ambient-platform.com,REJECT
DOMAIN-SUFFIX,local-media.ambient-platform.com,REJECT
DOMAIN-SUFFIX,local-media.m.ambient-platform.com,REJECT
DOMAIN-SUFFIX,metrics.ambient-platform.com,REJECT
DOMAIN-SUFFIX,retg.ambient-platform.com,REJECT
DOMAIN-SUFFIX,static.ambient-platform.com,REJECT
DOMAIN-SUFFIX,www.ambient-platform.com,REJECT
# [ambientdsp.com]
DOMAIN-SUFFIX,ambientdsp.com,REJECT
DOMAIN-SUFFIX,clk.ambientdsp.com,REJECT
DOMAIN-SUFFIX,cm.ambientdsp.com,REJECT
DOMAIN-SUFFIX,imp.ambientdsp.com,REJECT
DOMAIN-SUFFIX,metrics.ambientdsp.com,REJECT
DOMAIN-SUFFIX,static.ambientdsp.com,REJECT
DOMAIN-SUFFIX,trk.ambientdsp.com,REJECT
DOMAIN-SUFFIX,www.ambientdsp.com,REJECT
# [ambientplatform.vn]
DOMAIN-SUFFIX,ambientplatform.vn,REJECT
DOMAIN-SUFFIX,campaigns.ambientplatform.vn,REJECT
DOMAIN-SUFFIX,cdn.ambientplatform.vn,REJECT
DOMAIN-SUFFIX,cdn.m.ambientplatform.vn,REJECT
DOMAIN-SUFFIX,click.m.ambientplatform.vn,REJECT
DOMAIN-SUFFIX,delivery.m.ambientplatform.vn,REJECT
DOMAIN-SUFFIX,imp.m.ambientplatform.vn,REJECT
DOMAIN-SUFFIX,media.ambientplatform.vn,REJECT
DOMAIN-SUFFIX,media.m.ambientplatform.vn,REJECT
DOMAIN-SUFFIX,metrics.m.ambientplatform.vn,REJECT
DOMAIN-SUFFIX,rd.ambientplatform.vn,REJECT
# [amcdn.vn]
DOMAIN-SUFFIX,amcdn.vn,REJECT
DOMAIN-SUFFIX,static.amcdn.vn,REJECT
# [amedigital.vn]
DOMAIN-SUFFIX,analytics.amedigital.vn,REJECT
# [ampproject.org]
DOMAIN-SUFFIX,ads-thanhnien-vn.cdn.ampproject.org,REJECT
DOMAIN-SUFFIX,ampproject.org,REJECT
DOMAIN-SUFFIX,anymind360-com.cdn.ampproject.org,REJECT
DOMAIN-SUFFIX,cdn-bongdadem-net.cdn.ampproject.org,REJECT
DOMAIN-SUFFIX,log-vietnamplus-vn.cdn.ampproject.org,REJECT
DOMAIN-SUFFIX,sbbanner-com.cdn.ampproject.org,REJECT
DOMAIN-SUFFIX,static-addtoany-com.cdn.ampproject.org,REJECT
DOMAIN-SUFFIX,v9banners-com.cdn.ampproject.org,REJECT
# [amung.us]
DOMAIN-SUFFIX,amung.us,REJECT
# [anatic.net]
DOMAIN-SUFFIX,360.anatic.net,REJECT
# [anhsangvacuocsong.vn]
DOMAIN-SUFFIX,adv.anhsangvacuocsong.vn,REJECT
# [anime47.com]
DOMAIN-SUFFIX,tracker.anime47.com,REJECT
# [anninhthudo.vn]
DOMAIN-SUFFIX,beta-log.anninhthudo.vn,REJECT
DOMAIN-SUFFIX,log.anninhthudo.vn,REJECT
# [anquan.org]
DOMAIN-SUFFIX,anquan.org,REJECT
# [anthill.vn]
DOMAIN-SUFFIX,analytics.anthill.vn,REJECT
DOMAIN-SUFFIX,anthill.vn,REJECT
DOMAIN-SUFFIX,atrack-a.anthill.vn,REJECT
DOMAIN-SUFFIX,c0-vcdn.anthill.vn,REJECT
DOMAIN-SUFFIX,c0.anthill.vn,REJECT
DOMAIN-SUFFIX,d.anthill.vn,REJECT
DOMAIN-SUFFIX,e-vcdn.anthill.vn,REJECT
DOMAIN-SUFFIX,e.anthill.vn,REJECT
DOMAIN-SUFFIX,i0-vcdn.anthill.vn,REJECT
DOMAIN-SUFFIX,i0.anthill.vn,REJECT
DOMAIN-SUFFIX,id.anthill.vn,REJECT
DOMAIN-SUFFIX,origin-c0.anthill.vn,REJECT
DOMAIN-SUFFIX,origin-e.anthill.vn,REJECT
DOMAIN-SUFFIX,origin-st-a.anthill.vn,REJECT
DOMAIN-SUFFIX,p.anthill.vn,REJECT
DOMAIN-SUFFIX,st-a-id.anthill.vn,REJECT
DOMAIN-SUFFIX,st-a.anthill.vn,REJECT
DOMAIN-SUFFIX,st-a1.anthill.vn,REJECT
DOMAIN-SUFFIX,st-analytics.anthill.vn,REJECT
DOMAIN-SUFFIX,st-ssp.anthill.vn,REJECT
DOMAIN-SUFFIX,st-vcdn.anthill.vn,REJECT
DOMAIN-SUFFIX,st.a.anthill.vn,REJECT
DOMAIN-SUFFIX,st.anthill.vn,REJECT
DOMAIN-SUFFIX,staging-e-vcdn.anthill.vn,REJECT
DOMAIN-SUFFIX,staging-e.anthill.vn,REJECT
DOMAIN-SUFFIX,v0-vcdn.anthill.vn,REJECT
DOMAIN-SUFFIX,v0.anthill.vn,REJECT
DOMAIN-SUFFIX,v3-ads-st-vcdn.anthill.vn,REJECT
DOMAIN-SUFFIX,v3-st-vcdn.anthill.vn,REJECT
DOMAIN-SUFFIX,vcdn.anthill.vn,REJECT
DOMAIN-SUFFIX,www.anthill.vn,REJECT
# [ants.vn]
DOMAIN-SUFFIX,a.ants.vn,REJECT
DOMAIN-SUFFIX,abs.ants.vn,REJECT
DOMAIN-SUFFIX,ad.ants.vn,REJECT
DOMAIN-SUFFIX,ads.ants.vn,REJECT
DOMAIN-SUFFIX,adx.ants.vn,REJECT
DOMAIN-SUFFIX,antalyser.ants.vn,REJECT
DOMAIN-SUFFIX,ants.vn,REJECT
DOMAIN-SUFFIX,api-app.ants.vn,REJECT
DOMAIN-SUFFIX,app.ants.vn,REJECT
DOMAIN-SUFFIX,apps.ants.vn,REJECT
DOMAIN-SUFFIX,au-insight.ants.vn,REJECT
DOMAIN-SUFFIX,au.ants.vn,REJECT
DOMAIN-SUFFIX,babe.ants.vn,REJECT
DOMAIN-SUFFIX,crm.ants.vn,REJECT
DOMAIN-SUFFIX,d.ants.vn,REJECT
DOMAIN-SUFFIX,developers.ants.vn,REJECT
DOMAIN-SUFFIX,dsp-d.ants.vn,REJECT
DOMAIN-SUFFIX,e.ants.vn,REJECT
DOMAIN-SUFFIX,insight.ants.vn,REJECT
DOMAIN-SUFFIX,m-a.ants.vn,REJECT
DOMAIN-SUFFIX,ma.ants.vn,REJECT
DOMAIN-SUFFIX,ogs.ants.vn,REJECT
DOMAIN-SUFFIX,oms-t.ants.vn,REJECT
DOMAIN-SUFFIX,p.ants.vn,REJECT
DOMAIN-SUFFIX,prebid.ants.vn,REJECT
DOMAIN-SUFFIX,schemas.ants.vn,REJECT
DOMAIN-SUFFIX,st-au.ants.vn,REJECT
DOMAIN-SUFFIX,staging-d-tiki.ants.vn,REJECT
DOMAIN-SUFFIX,staging-d.ants.vn,REJECT
DOMAIN-SUFFIX,t.ants.vn,REJECT
DOMAIN-SUFFIX,t.d.ants.vn,REJECT
DOMAIN-SUFFIX,tiki.ants.vn,REJECT
DOMAIN-SUFFIX,www.ants.vn,REJECT
# [anymind360.com]
DOMAIN-SUFFIX,anymind360.com,REJECT
DOMAIN-SUFFIX,stg.anymind360.com,REJECT
# [app-measurement.com]
DOMAIN-SUFFIX,app-measurement.com,REJECT
# [apple.com]
DOMAIN-SUFFIX,iad.apple.com,REJECT
DOMAIN-SUFFIX,iadsdk.apple.com,REJECT
# [appota.com]
DOMAIN-SUFFIX,ads.appota.com,REJECT
DOMAIN-SUFFIX,appota.com,REJECT
# [appsflyer.com]
DOMAIN-SUFFIX,appsflyer.com,REJECT
# [appwifi.com]
DOMAIN-SUFFIX,tracking.appwifi.com,REJECT
# [arttimes.vn]
DOMAIN-SUFFIX,thongke.arttimes.vn,REJECT
# [atdnetwork.com]
DOMAIN-SUFFIX,adserver.atdnetwork.com,REJECT
DOMAIN-SUFFIX,atdnetwork.com,REJECT
DOMAIN-SUFFIX,delivery.atdnetwork.com,REJECT
DOMAIN-SUFFIX,platform.atdnetwork.com,REJECT
DOMAIN-SUFFIX,static01.atdnetwork.com,REJECT
DOMAIN-SUFFIX,track.atdnetwork.com,REJECT
DOMAIN-SUFFIX,www.atdnetwork.com,REJECT
# [atp.vn]
DOMAIN-SUFFIX,aff.atp.vn,REJECT
# [autoads.asia]
DOMAIN-SUFFIX,alpha2.autoads.asia,REJECT
DOMAIN-SUFFIX,alphaapi.autoads.asia,REJECT
DOMAIN-SUFFIX,api.autoads.asia,REJECT
DOMAIN-SUFFIX,autoads.asia,REJECT
DOMAIN-SUFFIX,betaapi.autoads.asia,REJECT
DOMAIN-SUFFIX,betacdn.autoads.asia,REJECT
DOMAIN-SUFFIX,cdn.autoads.asia,REJECT
DOMAIN-SUFFIX,fcd.autoads.asia,REJECT
DOMAIN-SUFFIX,file.autoads.asia,REJECT
DOMAIN-SUFFIX,indo.autoads.asia,REJECT
DOMAIN-SUFFIX,mantis.autoads.asia,REJECT
DOMAIN-SUFFIX,pixel.autoads.asia,REJECT
DOMAIN-SUFFIX,tracking.autoads.asia,REJECT
DOMAIN-SUFFIX,www.autoads.asia,REJECT
DOMAIN-SUFFIX,xacthuc.autoads.asia,REJECT
# [autodaily.vn]
DOMAIN-SUFFIX,adsv2.autodaily.vn,REJECT
# [autosurf.vn]
DOMAIN-SUFFIX,adv.autosurf.vn,REJECT
# [avoadsservices.com]
DOMAIN-SUFFIX,avoadsservices.com,REJECT
DOMAIN-SUFFIX,www.avoadsservices.com,REJECT
# [b8zk2cl6bjs92j7ah8k2kzi92jf8ck9vj7v0z5bv2v3cj2azlp0c8z5vb7dt.me]
DOMAIN-SUFFIX,b8zk2cl6bjs92j7ah8k2kzi92jf8ck9vj7v0z5bv2v3cj2azlp0c8z5vb7dt.me,REJECT
# [bachtuongphat.com]
DOMAIN-SUFFIX,analytics.bachtuongphat.com,REJECT
# [bantheme.xyz]
DOMAIN-SUFFIX,matomo.bantheme.xyz,REJECT
# [baobinhduong.vn]
DOMAIN-SUFFIX,ads.baobinhduong.vn,REJECT
# [baocamau.vn]
DOMAIN-SUFFIX,ads.baocamau.vn,REJECT
# [baocaobang.vn]
DOMAIN-SUFFIX,log.baocaobang.vn,REJECT
# [baodantoc.vn]
DOMAIN-SUFFIX,analytic.baodantoc.vn,REJECT
# [baodatviet.vn]
DOMAIN-SUFFIX,ads.baodatviet.vn,REJECT
DOMAIN-SUFFIX,log.baodatviet.vn,REJECT
# [baodauthau.vn]
DOMAIN-SUFFIX,log.baodauthau.vn,REJECT
# [baogiaothong.vn]
DOMAIN-SUFFIX,thongke99.baogiaothong.vn,REJECT
# [baohaiduong.vn]
DOMAIN-SUFFIX,ads.baohaiduong.vn,REJECT
# [baohatinh.vn]
DOMAIN-SUFFIX,log.baohatinh.vn,REJECT
# [baolaocai.vn]
DOMAIN-SUFFIX,log.baolaocai.vn,REJECT
# [baolongan.vn]
DOMAIN-SUFFIX,ads.baolongan.vn,REJECT
DOMAIN-SUFFIX,adx.baolongan.vn,REJECT
# [baomoi.com]
DOMAIN-SUFFIX,invite.baomoi.com,REJECT
DOMAIN-SUFFIX,log.baomoi.com,REJECT
DOMAIN-SUFFIX,za.baomoi.com,REJECT
# [baonghean.vn]
DOMAIN-SUFFIX,log.baonghean.vn,REJECT
# [baophapluat.vn]
DOMAIN-SUFFIX,log.baophapluat.vn,REJECT
# [baotainguyenmoitruong.vn]
DOMAIN-SUFFIX,ads.baotainguyenmoitruong.vn,REJECT
# [baotayninh.vn]
DOMAIN-SUFFIX,adv.baotayninh.vn,REJECT
# [baotintuc.vn]
DOMAIN-SUFFIX,adv.baotintuc.vn,REJECT
DOMAIN-SUFFIX,dantocmiennui-log.baotintuc.vn,REJECT
DOMAIN-SUFFIX,log-video.baotintuc.vn,REJECT
DOMAIN-SUFFIX,thongke.baotintuc.vn,REJECT
# [baovanhoa.vn]
DOMAIN-SUFFIX,log.baovanhoa.vn,REJECT
# [beecost.com]
DOMAIN-SUFFIX,log.beecost.com,REJECT
# [beecost.vn]
DOMAIN-SUFFIX,log.beecost.vn,REJECT
# [bidgear-syndication.com]
DOMAIN-SUFFIX,bidgear-syndication.com,REJECT
# [bidgear.com]
DOMAIN-SUFFIX,asset.bidgear.com,REJECT
DOMAIN-SUFFIX,bidgear.com,REJECT
DOMAIN-SUFFIX,cdn.bidgear.com,REJECT
DOMAIN-SUFFIX,demand.bidgear.com,REJECT
DOMAIN-SUFFIX,dsp.bidgear.com,REJECT
DOMAIN-SUFFIX,imp-dsp.bidgear.com,REJECT
DOMAIN-SUFFIX,imp8.bidgear.com,REJECT
DOMAIN-SUFFIX,imp9.bidgear.com,REJECT
DOMAIN-SUFFIX,media.bidgear.com,REJECT
DOMAIN-SUFFIX,pixel-dsp.bidgear.com,REJECT
DOMAIN-SUFFIX,platform.bidgear.com,REJECT
DOMAIN-SUFFIX,source.bidgear.com,REJECT
DOMAIN-SUFFIX,vn-platform.bidgear.com,REJECT
DOMAIN-SUFFIX,www.bidgear.com,REJECT
DOMAIN-SUFFIX,zabbix.bidgear.com,REJECT
# [bigstoreminigames.space]
DOMAIN-SUFFIX,bigstoreminigames.space,REJECT
# [biphim.club]
DOMAIN-SUFFIX,tvc.biphim.club,REJECT
# [bizfly.vn]
DOMAIN-SUFFIX,bizfly.vn,REJECT
# [bizlive.vn]
DOMAIN-SUFFIX,log.bizlive.vn,REJECT
# [bizweb.vn]
DOMAIN-SUFFIX,stats.bizweb.vn,REJECT
# [bkav.com]
DOMAIN-SUFFIX,analytics.bkav.com,REJECT
# [bkitsoftware.com]
DOMAIN-SUFFIX,ads.bkitsoftware.com,REJECT
# [bloggiamgia.info]
DOMAIN-SUFFIX,bloggiamgia.info,REJECT
# [blogtruyen.vn]
DOMAIN-SUFFIX,qcv5.blogtruyen.vn,REJECT
# [blogtruyenmoi.com]
DOMAIN-SUFFIX,qcv5.blogtruyenmoi.com,REJECT
# [blueseed.tv]
DOMAIN-SUFFIX,blueseed.tv,REJECT
# [bncloudfl.com]
DOMAIN-SUFFIX,bncloudfl.com,REJECT
# [boclinkads.com]
DOMAIN-SUFFIX,api.boclinkads.com,REJECT
DOMAIN-SUFFIX,api2.boclinkads.com,REJECT
# [bongdadem.net]
DOMAIN-SUFFIX,bongdadem.net,REJECT
DOMAIN-SUFFIX,cdn.bongdadem.net,REJECT
# [bookingcare.vn]
DOMAIN-SUFFIX,thongke.bookingcare.vn,REJECT
# [botbanhang.vn]
DOMAIN-SUFFIX,ads.botbanhang.vn,REJECT
DOMAIN-SUFFIX,botbanhang.vn,REJECT
DOMAIN-SUFFIX,chatbox-static.botbanhang.vn,REJECT
DOMAIN-SUFFIX,chatbox-tracking.botbanhang.vn,REJECT
DOMAIN-SUFFIX,chatbox-widget.botbanhang.vn,REJECT
# [bubblyzucchini.com]
DOMAIN-SUFFIX,bubblyzucchini.com,REJECT
# [bugsnag.com]
DOMAIN-SUFFIX,api.bugsnag.com,REJECT
DOMAIN-SUFFIX,app.bugsnag.com,REJECT
DOMAIN-SUFFIX,notify.bugsnag.com,REJECT
DOMAIN-SUFFIX,sessions.bugsnag.com,REJECT
# [businessstyle.vn]
DOMAIN-SUFFIX,ads.businessstyle.vn,REJECT
# [cache.vn]
DOMAIN-SUFFIX,cdn2.cache.vn,REJECT
# [cadovn.biz]
DOMAIN-SUFFIX,ads.cadovn.biz,REJECT
# [careerbuilder.vn]
DOMAIN-SUFFIX,ads.careerbuilder.vn,REJECT
DOMAIN-SUFFIX,ads1.careerbuilder.vn,REJECT
DOMAIN-SUFFIX,careerbuilder.vn,REJECT
# [careplusvn.com]
DOMAIN-SUFFIX,live.careplusvn.com,REJECT
# [caresoft.vn]
DOMAIN-SUFFIX,webchat.caresoft.vn,REJECT
# [carmudi.vn]
DOMAIN-SUFFIX,ads.carmudi.vn,REJECT
# [carnelbawrel.com]
DOMAIN-SUFFIX,carnelbawrel.com,REJECT
# [casso.vn]
DOMAIN-SUFFIX,casso.vn,REJECT
DOMAIN-SUFFIX,mautic.casso.vn,REJECT
# [cdnstoremedia.com]
DOMAIN-SUFFIX,cdnstoremedia.com,REJECT
DOMAIN-SUFFIX,static.cdnstoremedia.com,REJECT
DOMAIN-SUFFIX,vp.cdnstoremedia.com,REJECT
# [cdp.asia]
DOMAIN-SUFFIX,a.cdp.asia,REJECT
DOMAIN-SUFFIX,app.cdp.asia,REJECT
DOMAIN-SUFFIX,cdp.asia,REJECT
DOMAIN-SUFFIX,delivery-cloud.cdp.asia,REJECT
DOMAIN-SUFFIX,delivery.cdp.asia,REJECT
DOMAIN-SUFFIX,st-a.cdp.asia,REJECT
DOMAIN-SUFFIX,st-e.cdp.asia,REJECT
DOMAIN-SUFFIX,www.cdp.asia,REJECT
# [cdvn.vip]
DOMAIN-SUFFIX,ads.cdvn.vip,REJECT
# [cgv.vn]
DOMAIN-SUFFIX,advserver.cgv.vn,REJECT
DOMAIN-SUFFIX,mto.cgv.vn,REJECT
# [ch6p2aj2gh8zy5cm0px9ow7aj3tmzhtk6lzx2ch9xj7gx2jq1cj8v4jklz6b.me]
DOMAIN-SUFFIX,ch6p2aj2gh8zy5cm0px9ow7aj3tmzhtk6lzx2ch9xj7gx2jq1cj8v4jklz6b.me,REJECT
# [chanhtuoi.com]
DOMAIN-SUFFIX,ads.chanhtuoi.com,REJECT
# [channelvn.net]
DOMAIN-SUFFIX,logscafef.channelvn.net,REJECT
# [chaseherbalpasty.com]
DOMAIN-SUFFIX,chaseherbalpasty.com,REJECT
# [chetaomaysaigon.vn]
DOMAIN-SUFFIX,chetaomaysaigon.vn,REJECT
DOMAIN-SUFFIX,mautic.chetaomaysaigon.vn,REJECT
# [chiaki.vn]
DOMAIN-SUFFIX,affiliate.chiaki.vn,REJECT
DOMAIN-SUFFIX,clicker.chiaki.vn,REJECT
# [chieuhoa.com]
DOMAIN-SUFFIX,ad.chieuhoa.com,REJECT
DOMAIN-SUFFIX,chieuhoa.com,REJECT
# [chinmedia.vn]
DOMAIN-SUFFIX,adx.chinmedia.vn,REJECT
# [citadelpathstatue.com]
DOMAIN-SUFFIX,citadelpathstatue.com,REJECT
# [cityads.com]
DOMAIN-SUFFIX,adv.cityads.com,REJECT
DOMAIN-SUFFIX,ali.cityads.com,REJECT
DOMAIN-SUFFIX,aliexpress-summer.cityads.com,REJECT
DOMAIN-SUFFIX,api.cityads.com,REJECT
DOMAIN-SUFFIX,auth.cityads.com,REJECT
DOMAIN-SUFFIX,auth2.cityads.com,REJECT
DOMAIN-SUFFIX,cdn.cityads.com,REJECT
DOMAIN-SUFFIX,cdn77.cityads.com,REJECT
DOMAIN-SUFFIX,challenge.cityads.com,REJECT
DOMAIN-SUFFIX,checker.cityads.com,REJECT
DOMAIN-SUFFIX,cityads.com,REJECT
DOMAIN-SUFFIX,cnt.cityads.com,REJECT
DOMAIN-SUFFIX,demobl.cityads.com,REJECT
DOMAIN-SUFFIX,developers.cityads.com,REJECT
DOMAIN-SUFFIX,dsp.cityads.com,REJECT
DOMAIN-SUFFIX,finance.cityads.com,REJECT
DOMAIN-SUFFIX,games.cityads.com,REJECT
DOMAIN-SUFFIX,geo.cityads.com,REJECT
DOMAIN-SUFFIX,grand-prix.cityads.com,REJECT
DOMAIN-SUFFIX,infiniti.cityads.com,REJECT
DOMAIN-SUFFIX,join.cityads.com,REJECT
DOMAIN-SUFFIX,keitaro1.cityads.com,REJECT
DOMAIN-SUFFIX,love.cityads.com,REJECT
DOMAIN-SUFFIX,m.cityads.com,REJECT
DOMAIN-SUFFIX,market.cityads.com,REJECT
DOMAIN-SUFFIX,mvas.cityads.com,REJECT
DOMAIN-SUFFIX,mx00.cityads.com,REJECT
DOMAIN-SUFFIX,mxs01.cityads.com,REJECT
DOMAIN-SUFFIX,mxs02.cityads.com,REJECT
DOMAIN-SUFFIX,new.cityads.com,REJECT
DOMAIN-SUFFIX,nl-geo.cityads.com,REJECT
DOMAIN-SUFFIX,o.cityads.com,REJECT
DOMAIN-SUFFIX,out1.cityads.com,REJECT
DOMAIN-SUFFIX,out2.cityads.com,REJECT
DOMAIN-SUFFIX,out3.cityads.com,REJECT
DOMAIN-SUFFIX,promo.cityads.com,REJECT
DOMAIN-SUFFIX,redmine.cityads.com,REJECT
DOMAIN-SUFFIX,ru-geo.cityads.com,REJECT
DOMAIN-SUFFIX,september.cityads.com,REJECT
DOMAIN-SUFFIX,sg.cityads.com,REJECT
DOMAIN-SUFFIX,tinkoff.cityads.com,REJECT
DOMAIN-SUFFIX,us-geo.cityads.com,REJECT
DOMAIN-SUFFIX,wp-cdn.cityads.com,REJECT
DOMAIN-SUFFIX,www.cityads.com,REJECT
# [cityadstrack.com]
DOMAIN-SUFFIX,cityadstrack.com,REJECT
DOMAIN-SUFFIX,p.cityadstrack.com,REJECT
DOMAIN-SUFFIX,stats.cityadstrack.com,REJECT
# [cleverads.vn]
DOMAIN-SUFFIX,business.cleverads.vn,REJECT
DOMAIN-SUFFIX,cleverads.vn,REJECT
DOMAIN-SUFFIX,showcase.cleverads.vn,REJECT
DOMAIN-SUFFIX,tool.cleverads.vn,REJECT
DOMAIN-SUFFIX,widget.cleverads.vn,REJECT
DOMAIN-SUFFIX,wifiads.cleverads.vn,REJECT
DOMAIN-SUFFIX,www.cleverads.vn,REJECT
# [clevernet.vn]
DOMAIN-SUFFIX,clevernet.vn,REJECT
DOMAIN-SUFFIX,m.clevernet.vn,REJECT
DOMAIN-SUFFIX,www.clevernet.vn,REJECT
# [clgt.xyz]
DOMAIN-SUFFIX,clgt.xyz,REJECT
# [clipbongda.info]
DOMAIN-SUFFIX,clipbongda.info,REJECT
# [clix.vn]
DOMAIN-SUFFIX,clix.vn,REJECT
# [cloudfront.net]
DOMAIN-SUFFIX,cloudfront.net,REJECT
# [cloudify.vn]
DOMAIN-SUFFIX,cloudify.vn,REJECT
DOMAIN-SUFFIX,mautic.cloudify.vn,REJECT
# [cloudlinks.cn]
DOMAIN-SUFFIX,advertise.cloudlinks.cn,REJECT
# [cnnd.vn]
DOMAIN-SUFFIX,cnnd.vn,REJECT
DOMAIN-SUFFIX,logg4u.cnnd.vn,REJECT
DOMAIN-SUFFIX,sharefb.cnnd.vn,REJECT
DOMAIN-SUFFIX,v20.cnnd.vn,REJECT
# [cntqk.com]
DOMAIN-SUFFIX,s.cntqk.com,REJECT
# [cntqk.vn]
DOMAIN-SUFFIX,s.cntqk.vn,REJECT
# [coccoc.com]
DOMAIN-SUFFIX,api.qc.coccoc.com,REJECT
DOMAIN-SUFFIX,banners-gallery.coccoc.com,REJECT
DOMAIN-SUFFIX,catalog.qc.coccoc.com,REJECT
DOMAIN-SUFFIX,cdn-qc.coccoc.com,REJECT
DOMAIN-SUFFIX,cdn.comedia.coccoc.com,REJECT
DOMAIN-SUFFIX,cdn.qc.coccoc.com,REJECT
DOMAIN-SUFFIX,context.qc.coccoc.com,REJECT
DOMAIN-SUFFIX,cp.qc.coccoc.com,REJECT
DOMAIN-SUFFIX,display.qc.coccoc.com,REJECT
DOMAIN-SUFFIX,metrics.coccoc.com,REJECT
DOMAIN-SUFFIX,ntrb.qc.coccoc.com,REJECT
DOMAIN-SUFFIX,pixel.coccoc.com,REJECT
DOMAIN-SUFFIX,qc-static.coccoc.com,REJECT
DOMAIN-SUFFIX,qc.coccoc.com,REJECT
DOMAIN-SUFFIX,searcher.qc.coccoc.com,REJECT
DOMAIN-SUFFIX,shop-cdn.coccoc.com,REJECT
DOMAIN-SUFFIX,ssp.qc.coccoc.com,REJECT
# [coccoc.vn]
DOMAIN-SUFFIX,qc.coccoc.vn,REJECT
# [cococx.com]
DOMAIN-SUFFIX,ccx.cococx.com,REJECT
DOMAIN-SUFFIX,cd.cococx.com,REJECT
DOMAIN-SUFFIX,cdp.cococx.com,REJECT
DOMAIN-SUFFIX,gs.cococx.com,REJECT
# [codon.vn]
DOMAIN-SUFFIX,codon.vn,REJECT
DOMAIN-SUFFIX,rp.codon.vn,REJECT
DOMAIN-SUFFIX,s2.codon.vn,REJECT
DOMAIN-SUFFIX,wpn.codon.vn,REJECT
DOMAIN-SUFFIX,www.codon.vn,REJECT
DOMAIN-SUFFIX,xads.codon.vn,REJECT
DOMAIN-SUFFIX,xmadsapi.codon.vn,REJECT
# [com.vn]
DOMAIN-SUFFIX,ad-ndtv.3s.com.vn,REJECT
DOMAIN-SUFFIX,ad.24h.com.vn,REJECT
DOMAIN-SUFFIX,ad.icheck.com.vn,REJECT
DOMAIN-SUFFIX,admin.voh.com.vn,REJECT
DOMAIN-SUFFIX,ads.autonet.com.vn,REJECT
DOMAIN-SUFFIX,ads.baoangiang.com.vn,REJECT
DOMAIN-SUFFIX,ads.baobinhthuan.com.vn,REJECT
DOMAIN-SUFFIX,ads.baocantho.com.vn,REJECT
DOMAIN-SUFFIX,ads.phunuonline.com.vn,REJECT
DOMAIN-SUFFIX,ads.suckhoegiadinh.com.vn,REJECT
DOMAIN-SUFFIX,adt.com.vn,REJECT
DOMAIN-SUFFIX,adv.baoangiang.com.vn,REJECT
DOMAIN-SUFFIX,adver.24h.com.vn,REJECT
DOMAIN-SUFFIX,analytics.admon.com.vn,REJECT
DOMAIN-SUFFIX,analytics.bkav.com.vn,REJECT
DOMAIN-SUFFIX,analytics.evn.com.vn,REJECT
DOMAIN-SUFFIX,analytics.fsoft.com.vn,REJECT
DOMAIN-SUFFIX,analytics.ntlc.com.vn,REJECT
DOMAIN-SUFFIX,api.subiz.com.vn,REJECT
DOMAIN-SUFFIX,app.subiz.com.vn,REJECT
DOMAIN-SUFFIX,autonet.com.vn,REJECT
DOMAIN-SUFFIX,cdptracker.hocmai.com.vn,REJECT
DOMAIN-SUFFIX,counter.24h.com.vn,REJECT
DOMAIN-SUFFIX,delivery.doisongphapluat.com.vn,REJECT
DOMAIN-SUFFIX,delivery.vtcnew.com.vn,REJECT
DOMAIN-SUFFIX,digi.vinut.com.vn,REJECT
DOMAIN-SUFFIX,embed.wiinvent.com.vn,REJECT
DOMAIN-SUFFIX,icheck.com.vn,REJECT
DOMAIN-SUFFIX,intranet.dcorp.com.vn,REJECT
DOMAIN-SUFFIX,log.baobackan.com.vn,REJECT
DOMAIN-SUFFIX,log.baogialai.com.vn,REJECT
DOMAIN-SUFFIX,log.hemera.com.vn,REJECT
DOMAIN-SUFFIX,log.oto.com.vn,REJECT
DOMAIN-SUFFIX,log.saigondautu.com.vn,REJECT
DOMAIN-SUFFIX,log.xoso.com.vn,REJECT
DOMAIN-SUFFIX,logapi.misa.com.vn,REJECT
DOMAIN-SUFFIX,logs.docnhanh.com.vn,REJECT
DOMAIN-SUFFIX,logsbin.dantri.com.vn,REJECT
DOMAIN-SUFFIX,measure.pti.com.vn,REJECT
DOMAIN-SUFFIX,measure.vndirect.com.vn,REJECT
DOMAIN-SUFFIX,qctt24h.24h.com.vn,REJECT
DOMAIN-SUFFIX,quangcao.24h.com.vn,REJECT
DOMAIN-SUFFIX,quangcao.fff.com.vn,REJECT
DOMAIN-SUFFIX,slm.dantri.com.vn,REJECT
DOMAIN-SUFFIX,statistic.batdongsan.com.vn,REJECT
DOMAIN-SUFFIX,statistics.tapchimypham.com.vn,REJECT
DOMAIN-SUFFIX,subiz.com.vn,REJECT
DOMAIN-SUFFIX,thongke.24h.com.vn,REJECT
DOMAIN-SUFFIX,track.icheck.com.vn,REJECT
DOMAIN-SUFFIX,track.pnj.com.vn,REJECT
DOMAIN-SUFFIX,tracking.dantri.com.vn,REJECT
DOMAIN-SUFFIX,tracking.fff.com.vn,REJECT
DOMAIN-SUFFIX,tracking.vtcnew.com.vn,REJECT
DOMAIN-SUFFIX,wiinvent.com.vn,REJECT
DOMAIN-SUFFIX,www.adt.com.vn,REJECT
# [concung.com]
DOMAIN-SUFFIX,tracer.concung.com,REJECT
# [contineljs.com]
DOMAIN-SUFFIX,cdn.contineljs.com,REJECT
DOMAIN-SUFFIX,contineljs.com,REJECT
DOMAIN-SUFFIX,defaultdsp.contineljs.com,REJECT
DOMAIN-SUFFIX,static.contineljs.com,REJECT
# [coosync.com]
DOMAIN-SUFFIX,coosync.com,REJECT
# [crocopop.com]
DOMAIN-SUFFIX,crocopop.com,REJECT
# [cungcau.vn]
DOMAIN-SUFFIX,ads.cungcau.vn,REJECT
# [cystack.net]
DOMAIN-SUFFIX,tracking.cystack.net,REJECT
# [dable.io]
DOMAIN-SUFFIX,ad-log.dable.io,REJECT
DOMAIN-SUFFIX,admin.dable.io,REJECT
DOMAIN-SUFFIX,adx.dable.io,REJECT
DOMAIN-SUFFIX,api.dable.io,REJECT
DOMAIN-SUFFIX,dable.io,REJECT
DOMAIN-SUFFIX,dsp.dable.io,REJECT
DOMAIN-SUFFIX,images.dable.io,REJECT
DOMAIN-SUFFIX,k8s.dable.io,REJECT
DOMAIN-SUFFIX,marketing.dable.io,REJECT
DOMAIN-SUFFIX,news.dable.io,REJECT
DOMAIN-SUFFIX,r-log.dable.io,REJECT
DOMAIN-SUFFIX,redirect.dable.io,REJECT
DOMAIN-SUFFIX,sp-api.dable.io,REJECT
DOMAIN-SUFFIX,sp-r.dable.io,REJECT
DOMAIN-SUFFIX,static.dable.io,REJECT
DOMAIN-SUFFIX,thumb.dable.io,REJECT
DOMAIN-SUFFIX,www.dable.io,REJECT
# [daibieunhandan.vn]
DOMAIN-SUFFIX,log.daibieunhandan.vn,REJECT
# [daidoanket.vn]
DOMAIN-SUFFIX,log.daidoanket.vn,REJECT
DOMAIN-SUFFIX,newlog.daidoanket.vn,REJECT
# [daleriki.com]
DOMAIN-SUFFIX,cdnstatic.daleriki.com,REJECT
DOMAIN-SUFFIX,daleriki.com,REJECT
DOMAIN-SUFFIX,iki.daleriki.com,REJECT
# [dantocmiennui.vn]
DOMAIN-SUFFIX,dantocmiennui.vn,REJECT
DOMAIN-SUFFIX,log.dantocmiennui.vn,REJECT
DOMAIN-SUFFIX,logkm.dantocmiennui.vn,REJECT
DOMAIN-SUFFIX,logzh.dantocmiennui.vn,REJECT
# [demopage.me]
DOMAIN-SUFFIX,demopage.me,REJECT
# [deqik.com]
DOMAIN-SUFFIX,deqik.com,REJECT
# [designervn.net]
DOMAIN-SUFFIX,designervn.net,REJECT
DOMAIN-SUFFIX,qc.designervn.net,REJECT
# [diagramjawlineunhappy.com]
DOMAIN-SUFFIX,diagramjawlineunhappy.com,REJECT
# [dieuviet.com]
DOMAIN-SUFFIX,mobileads.dieuviet.com,REJECT
# [digi8.vn]
DOMAIN-SUFFIX,analytics.digi8.vn,REJECT
# [distinctrobin.com]
DOMAIN-SUFFIX,agt.distinctrobin.com,REJECT
DOMAIN-SUFFIX,dfw.distinctrobin.com,REJECT
DOMAIN-SUFFIX,distinctrobin.com,REJECT
DOMAIN-SUFFIX,gko.distinctrobin.com,REJECT
DOMAIN-SUFFIX,imeg.distinctrobin.com,REJECT
DOMAIN-SUFFIX,obin.distinctrobin.com,REJECT
# [dmca.com]
DOMAIN-SUFFIX,images.dmca.com,REJECT
# [doanhnhan.vn]
DOMAIN-SUFFIX,log.doanhnhan.vn,REJECT
# [donglogs.com]
DOMAIN-SUFFIX,analytics.donglogs.com,REJECT
DOMAIN-SUFFIX,api.donglogs.com,REJECT
DOMAIN-SUFFIX,donglogs.com,REJECT
DOMAIN-SUFFIX,rec.donglogs.com,REJECT
DOMAIN-SUFFIX,scripts.donglogs.com,REJECT
DOMAIN-SUFFIX,www.donglogs.com,REJECT
# [dongphim.net]
DOMAIN-SUFFIX,an.dongphim.net,REJECT
DOMAIN-SUFFIX,stats.dongphim.net,REJECT
# [doubleclick.net]
DOMAIN-SUFFIX,doubleclick.net,REJECT
# [dsp.vn]
DOMAIN-SUFFIX,statis.dsp.vn,REJECT
# [dtadnetwork.com]
DOMAIN-SUFFIX,dtadnetwork.com,REJECT
DOMAIN-SUFFIX,static.dtadnetwork.com,REJECT
# [duamilsyr.com]
DOMAIN-SUFFIX,duamilsyr.com,REJECT
# [dubaotiente.com]
DOMAIN-SUFFIX,log.dubaotiente.com,REJECT
# [e7z9t4x6a0v5mk3zo1a0xj2z7c6g8sa6js5z7s2c3h9x0s5fh3a6sjwb8q7m.xyz]
DOMAIN-SUFFIX,e7z9t4x6a0v5mk3zo1a0xj2z7c6g8sa6js5z7s2c3h9x0s5fh3a6sjwb8q7m.xyz,REJECT
# [easygroup.vn]
DOMAIN-SUFFIX,easygroup.vn,REJECT
DOMAIN-SUFFIX,mautic.easygroup.vn,REJECT
# [eclick.vn]
DOMAIN-SUFFIX,admin.iad.eclick.vn,REJECT
DOMAIN-SUFFIX,analytics.eclick.vn,REJECT
DOMAIN-SUFFIX,c.d.eclick.vn,REJECT
DOMAIN-SUFFIX,c.eclick.vn,REJECT
DOMAIN-SUFFIX,cpm.d.eclick.vn,REJECT
DOMAIN-SUFFIX,cpm.eclick.vn,REJECT
DOMAIN-SUFFIX,cpm.j.eclick.vn,REJECT
DOMAIN-SUFFIX,d.eclick.vn,REJECT
DOMAIN-SUFFIX,dmp.eclick.vn,REJECT
DOMAIN-SUFFIX,e.eclick.vn,REJECT
DOMAIN-SUFFIX,eclick.vn,REJECT
DOMAIN-SUFFIX,emarketing.eclick.vn,REJECT
DOMAIN-SUFFIX,g.eclick.vn,REJECT
DOMAIN-SUFFIX,iad.eclick.vn,REJECT
DOMAIN-SUFFIX,img.eclick.vn,REJECT
DOMAIN-SUFFIX,imgportal.eclick.vn,REJECT
DOMAIN-SUFFIX,j.eclick.vn,REJECT
DOMAIN-SUFFIX,l.a.eclick.vn,REJECT
DOMAIN-SUFFIX,l.d.eclick.vn,REJECT
DOMAIN-SUFFIX,la.eclick.vn,REJECT
DOMAIN-SUFFIX,la2.eclick.vn,REJECT
DOMAIN-SUFFIX,log.d.eclick.vn,REJECT
DOMAIN-SUFFIX,log.eclick.vn,REJECT
DOMAIN-SUFFIX,log.pv.eclick.vn,REJECT
DOMAIN-SUFFIX,log.pv1.eclick.vn,REJECT
DOMAIN-SUFFIX,r.eclick.vn,REJECT
DOMAIN-SUFFIX,rtb.eclick.vn,REJECT
DOMAIN-SUFFIX,s.eclick.vn,REJECT
DOMAIN-SUFFIX,scdn.eclick.vn,REJECT
DOMAIN-SUFFIX,st.a.eclick.vn,REJECT
DOMAIN-SUFFIX,st.admin.iad.eclick.vn,REJECT
DOMAIN-SUFFIX,st.eclick.vn,REJECT
DOMAIN-SUFFIX,st.l.a.eclick.vn,REJECT
DOMAIN-SUFFIX,staging.j.eclick.vn,REJECT
DOMAIN-SUFFIX,static.eclick.vn,REJECT
DOMAIN-SUFFIX,stiad.eclick.vn,REJECT
DOMAIN-SUFFIX,stla.eclick.vn,REJECT
DOMAIN-SUFFIX,stportal.eclick.vn,REJECT
DOMAIN-SUFFIX,t.d.eclick.vn,REJECT
DOMAIN-SUFFIX,t.eclick.vn,REJECT
DOMAIN-SUFFIX,tracking.eclick.vn,REJECT
DOMAIN-SUFFIX,www.eclick.vn,REJECT
# [ecoe.vn]
DOMAIN-SUFFIX,matomo.ecoe.vn,REJECT
# [edu.vn]
DOMAIN-SUFFIX,log.dav.edu.vn,REJECT
DOMAIN-SUFFIX,mautic-learn.teky.edu.vn,REJECT
DOMAIN-SUFFIX,mautic.teky.edu.vn,REJECT
DOMAIN-SUFFIX,seo.cloud.edu.vn,REJECT
DOMAIN-SUFFIX,track.vio.edu.vn,REJECT
# [educa.vn]
DOMAIN-SUFFIX,educa.vn,REJECT
DOMAIN-SUFFIX,mautic.educa.vn,REJECT
# [educe.vn]
DOMAIN-SUFFIX,mautic.educe.vn,REJECT
# [edupia.vn]
DOMAIN-SUFFIX,tracker.edupia.vn,REJECT
# [epicdn.me]
DOMAIN-SUFFIX,epicdn.me,REJECT
DOMAIN-SUFFIX,log-baodauthau.epicdn.me,REJECT
DOMAIN-SUFFIX,log-baogialai.epicdn.me,REJECT
DOMAIN-SUFFIX,log-baolaocai.epicdn.me,REJECT
DOMAIN-SUFFIX,log-dttc-sggp.epicdn.me,REJECT
DOMAIN-SUFFIX,log-en-nhandan.epicdn.me,REJECT
DOMAIN-SUFFIX,log-en-sggp.epicdn.me,REJECT
DOMAIN-SUFFIX,log-giaoduc.epicdn.me,REJECT
DOMAIN-SUFFIX,log-giaoducthoidai.epicdn.me,REJECT
DOMAIN-SUFFIX,log-kienthucnet.epicdn.me,REJECT
DOMAIN-SUFFIX,log-mekongasean.epicdn.me,REJECT
DOMAIN-SUFFIX,log-nhandan.epicdn.me,REJECT
DOMAIN-SUFFIX,log-thanhnien.epicdn.me,REJECT
DOMAIN-SUFFIX,log-thuonggiaonline.epicdn.me,REJECT
DOMAIN-SUFFIX,log-tinnhanhchungkhoan.epicdn.me,REJECT
DOMAIN-SUFFIX,logv2-kienthuc.epicdn.me,REJECT
DOMAIN-SUFFIX,quangcao-thanhnien.epicdn.me,REJECT
# [etix.vn]
DOMAIN-SUFFIX,stats.etix.vn,REJECT
# [eva.vn]
DOMAIN-SUFFIX,ad.eva.vn,REJECT
# [evgcdn.net]
DOMAIN-SUFFIX,analytics.evgcdn.net,REJECT
# [exoclick.com]
DOMAIN-SUFFIX,exoclick.com,REJECT
# [explus.vn]
DOMAIN-SUFFIX,analytics.explus.vn,REJECT
# [ezca.asia]
DOMAIN-SUFFIX,api.ezca.asia,REJECT
DOMAIN-SUFFIX,cdn.ezca.asia,REJECT
DOMAIN-SUFFIX,ezca.asia,REJECT
DOMAIN-SUFFIX,recommender.ezca.asia,REJECT
DOMAIN-SUFFIX,wss.ezca.asia,REJECT
# [fado.vn]
DOMAIN-SUFFIX,tracker.fado.vn,REJECT
DOMAIN-SUFFIX,tracking.fado.vn,REJECT
# [farawayinstallation.com]
DOMAIN-SUFFIX,farawayinstallation.com,REJECT
# [fieryinjure.com]
DOMAIN-SUFFIX,fieryinjure.com,REJECT
# [file-subiz.com]
DOMAIN-SUFFIX,file-subiz.com,REJECT
# [filum.ai]
DOMAIN-SUFFIX,event.filum.ai,REJECT
# [firebaseapp.com]
DOMAIN-SUFFIX,stockbook-ads.firebaseapp.com,REJECT
# [firebaseio.com]
DOMAIN-SUFFIX,stockbook-ads.firebaseio.com,REJECT
# [fly-ads.net]
DOMAIN-SUFFIX,fly-ads.net,REJECT
DOMAIN-SUFFIX,tags.fly-ads.net,REJECT
# [flygame.io]
DOMAIN-SUFFIX,api.flygame.io,REJECT
DOMAIN-SUFFIX,flygame.io,REJECT
DOMAIN-SUFFIX,game.flygame.io,REJECT
DOMAIN-SUFFIX,images.flygame.io,REJECT
DOMAIN-SUFFIX,inapi.flygame.io,REJECT
DOMAIN-SUFFIX,ingame.flygame.io,REJECT
DOMAIN-SUFFIX,lottery.flygame.io,REJECT
DOMAIN-SUFFIX,stat.flygame.io,REJECT
DOMAIN-SUFFIX,thapi.flygame.io,REJECT
DOMAIN-SUFFIX,thgame.flygame.io,REJECT
# [foody.vn]
DOMAIN-SUFFIX,trackingapi.foody.vn,REJECT
# [foonerne.com]
DOMAIN-SUFFIX,foonerne.com,REJECT
# [formalhood.com]
DOMAIN-SUFFIX,formalhood.com,REJECT
# [fpt.shop]
DOMAIN-SUFFIX,fa.fpt.shop,REJECT
# [fpt.vn]
DOMAIN-SUFFIX,ads.fpt.vn,REJECT
DOMAIN-SUFFIX,ads8.fpt.vn,REJECT
# [fptad.com]
DOMAIN-SUFFIX,customers.fptad.com,REJECT
DOMAIN-SUFFIX,fptad.com,REJECT
DOMAIN-SUFFIX,img.customers.fptad.com,REJECT
DOMAIN-SUFFIX,static.customers.fptad.com,REJECT
# [fptplay.net]
DOMAIN-SUFFIX,ads-cdn.fptplay.net,REJECT
# [fuseplatform.net]
DOMAIN-SUFFIX,adasia.fuseplatform.net,REJECT
DOMAIN-SUFFIX,adireto.fuseplatform.net,REJECT
DOMAIN-SUFFIX,api.fuseplatform.net,REJECT
DOMAIN-SUFFIX,cdn.fuseplatform.net,REJECT
DOMAIN-SUFFIX,demo.fuseplatform.net,REJECT
DOMAIN-SUFFIX,fuseplatform.net,REJECT
DOMAIN-SUFFIX,staging.fuseplatform.net,REJECT
DOMAIN-SUFFIX,static.fuseplatform.net,REJECT
# [gameclick.vn]
DOMAIN-SUFFIX,csmads.gameclick.vn,REJECT
# [gameitop.com]
DOMAIN-SUFFIX,ng-vn-notice.gameitop.com,REJECT
# [gammaplatform.com]
DOMAIN-SUFFIX,app.gammaplatform.com,REJECT
DOMAIN-SUFFIX,clk.gammaplatform.com,REJECT
DOMAIN-SUFFIX,cm-supply-web.gammaplatform.com,REJECT
DOMAIN-SUFFIX,cm.gammaplatform.com,REJECT
DOMAIN-SUFFIX,d.gammaplatform.com,REJECT
DOMAIN-SUFFIX,gammaplatform.com,REJECT
DOMAIN-SUFFIX,hb.gammaplatform.com,REJECT
DOMAIN-SUFFIX,imp.gammaplatform.com,REJECT
DOMAIN-SUFFIX,imp2.gammaplatform.com,REJECT
DOMAIN-SUFFIX,in-view.gammaplatform.com,REJECT
DOMAIN-SUFFIX,login.gammaplatform.com,REJECT
DOMAIN-SUFFIX,static.gammaplatform.com,REJECT
DOMAIN-SUFFIX,stc.gammaplatform.com,REJECT
DOMAIN-SUFFIX,t.gammaplatform.com,REJECT
DOMAIN-SUFFIX,tag.gammaplatform.com,REJECT
DOMAIN-SUFFIX,track.gammaplatform.com,REJECT
DOMAIN-SUFFIX,www.gammaplatform.com,REJECT
# [gammassp.com]
DOMAIN-SUFFIX,advertising.gammassp.com,REJECT
DOMAIN-SUFFIX,gammassp.com,REJECT
DOMAIN-SUFFIX,test-places.gammassp.com,REJECT
DOMAIN-SUFFIX,www.gammassp.com,REJECT
# [gapone.vn]
DOMAIN-SUFFIX,tracking.gapone.vn,REJECT
# [geniee.jp]
DOMAIN-SUFFIX,geniee.jp,REJECT
# [genieesspv.jp]
DOMAIN-SUFFIX,genieesspv.jp,REJECT
# [genmonet.com]
DOMAIN-SUFFIX,gcjs.genmonet.com,REJECT
DOMAIN-SUFFIX,genmonet.com,REJECT
DOMAIN-SUFFIX,gl.genmonet.com,REJECT
# [getsentry.com]
DOMAIN-SUFFIX,app.getsentry.com,REJECT
# [ghtk.vn]
DOMAIN-SUFFIX,web-analytic.ghtk.vn,REJECT
# [giacngo.vn]
DOMAIN-SUFFIX,log.giacngo.vn,REJECT
# [giaminhmedia.vn]
DOMAIN-SUFFIX,admin.giaminhmedia.vn,REJECT
DOMAIN-SUFFIX,ads.giaminhmedia.vn,REJECT
# [giaoducthoidai.vn]
DOMAIN-SUFFIX,log.giaoducthoidai.vn,REJECT
DOMAIN-SUFFIX,s.giaoducthoidai.vn,REJECT
# [gitiho.com]
DOMAIN-SUFFIX,campaign.gitiho.com,REJECT
# [glodretsa.net]
DOMAIN-SUFFIX,glodretsa.net,REJECT
# [google.com]
DOMAIN-SUFFIX,adservice.google.com,REJECT
# [googleanalytics.com]
DOMAIN-SUFFIX,click.googleanalytics.com,REJECT
# [googlesyndication.com]
DOMAIN-SUFFIX,googlesyndication.com,REJECT
# [googletagmanager.com]
DOMAIN-SUFFIX,googletagmanager.com,REJECT
# [gostats.vn]
DOMAIN-SUFFIX,c1.gostats.vn,REJECT
DOMAIN-SUFFIX,c2.gostats.vn,REJECT
DOMAIN-SUFFIX,c3.gostats.vn,REJECT
DOMAIN-SUFFIX,c4.gostats.vn,REJECT
DOMAIN-SUFFIX,c5.gostats.vn,REJECT
DOMAIN-SUFFIX,gostats.vn,REJECT
DOMAIN-SUFFIX,www.gostats.vn,REJECT
# [gosu.vn]
DOMAIN-SUFFIX,ads.gosu.vn,REJECT
# [gotama.link]
DOMAIN-SUFFIX,analytics.gotama.link,REJECT
# [gov.vn]
DOMAIN-SUFFIX,analytic.angiang.gov.vn,REJECT
DOMAIN-SUFFIX,f-emc.ngsp.gov.vn,REJECT
DOMAIN-SUFFIX,tracking.tuyenquang.gov.vn,REJECT
DOMAIN-SUFFIX,us.mplis.gov.vn,REJECT
# [gtmjs.com]
DOMAIN-SUFFIX,gtmjs.com,REJECT
# [gullyending.com]
DOMAIN-SUFFIX,gullyending.com,REJECT
# [h6o2z0pwx5ja7dwxn0wx4fhv7mp0qoladm8vj6do4h1c6gja8evrn6g5fixk.me]
DOMAIN-SUFFIX,h6o2z0pwx5ja7dwxn0wx4fhv7mp0qoladm8vj6do4h1c6gja8evrn6g5fixk.me,REJECT
# [hapiwork.vn]
DOMAIN-SUFFIX,tracking.hapiwork.vn,REJECT
# [happynest.vn]
DOMAIN-SUFFIX,ad.happynest.vn,REJECT
DOMAIN-SUFFIX,happynest.vn,REJECT
# [haproinfo.vn]
DOMAIN-SUFFIX,haproinfo.vn,REJECT
DOMAIN-SUFFIX,mautic.haproinfo.vn,REJECT
# [hara.vn]
DOMAIN-SUFFIX,facebook-ads.hara.vn,REJECT
DOMAIN-SUFFIX,google-ads.hara.vn,REJECT
DOMAIN-SUFFIX,hara.vn,REJECT
DOMAIN-SUFFIX,stats.hara.vn,REJECT
DOMAIN-SUFFIX,tiktok-ads.hara.vn,REJECT
# [haraads.com]
DOMAIN-SUFFIX,apps.haraads.com,REJECT
# [harafunnel.com]
DOMAIN-SUFFIX,app.harafunnel.com,REJECT
DOMAIN-SUFFIX,assets.harafunnel.com,REJECT
# [haraloyalty.com]
DOMAIN-SUFFIX,app.haraloyalty.com,REJECT
# [harasocial.com]
DOMAIN-SUFFIX,app.harasocial.com,REJECT
# [haravan.com]
DOMAIN-SUFFIX,combo-omni.haravan.com,REJECT
DOMAIN-SUFFIX,facebookinbox-omni-onapp.haravan.com,REJECT
DOMAIN-SUFFIX,haravan.com,REJECT
DOMAIN-SUFFIX,onapp.haravan.com,REJECT
DOMAIN-SUFFIX,promotion.haravan.com,REJECT
DOMAIN-SUFFIX,socialloginplus-apps.haravan.com,REJECT
# [hbplatform.com]
DOMAIN-SUFFIX,cdn.hbplatform.com,REJECT
DOMAIN-SUFFIX,hbplatform.com,REJECT
DOMAIN-SUFFIX,static.hbplatform.com,REJECT
# [headlines.pw]
DOMAIN-SUFFIX,adadmin.headlines.pw,REJECT
DOMAIN-SUFFIX,adpostback.headlines.pw,REJECT
DOMAIN-SUFFIX,apia.headlines.pw,REJECT
DOMAIN-SUFFIX,apl.headlines.pw,REJECT
DOMAIN-SUFFIX,event.headlines.pw,REJECT
DOMAIN-SUFFIX,financial-agent.headlines.pw,REJECT
DOMAIN-SUFFIX,headlines.pw,REJECT
DOMAIN-SUFFIX,lottery.headlines.pw,REJECT
DOMAIN-SUFFIX,nstat.headlines.pw,REJECT
DOMAIN-SUFFIX,offerwall.headlines.pw,REJECT
DOMAIN-SUFFIX,stat.headlines.pw,REJECT
DOMAIN-SUFFIX,sv-api-event.headlines.pw,REJECT
DOMAIN-SUFFIX,sv-api-lottery.headlines.pw,REJECT
DOMAIN-SUFFIX,sv-static-lottery.headlines.pw,REJECT
DOMAIN-SUFFIX,sv-static1-lottery.headlines.pw,REJECT
DOMAIN-SUFFIX,user.headlines.pw,REJECT
DOMAIN-SUFFIX,widget.headlines.pw,REJECT
# [hebela.vn]
DOMAIN-SUFFIX,analytics.hebela.vn,REJECT
# [hellobacsi.com]
DOMAIN-SUFFIX,subot.hellobacsi.com,REJECT
# [hellohealthgroup.com]
DOMAIN-SUFFIX,event-tracking.hellohealthgroup.com,REJECT
# [henho24h.net]
DOMAIN-SUFFIX,henho24h.net,REJECT
# [hicity.vn]
DOMAIN-SUFFIX,hicity.vn,REJECT
DOMAIN-SUFFIX,matomo.hicity.vn,REJECT
DOMAIN-SUFFIX,mautic.hicity.vn,REJECT
# [hoabinh.vn]
DOMAIN-SUFFIX,matomo.quan.hoabinh.vn,REJECT
# [hoanghamobile.com]
DOMAIN-SUFFIX,mkt.hoanghamobile.com,REJECT
# [holahupa.com]
DOMAIN-SUFFIX,holahupa.com,REJECT
# [home.vn]
DOMAIN-SUFFIX,ads.home.vn,REJECT
# [homedy.com]
DOMAIN-SUFFIX,btrack.homedy.com,REJECT
DOMAIN-SUFFIX,s.homedy.com,REJECT
# [homedy.net]
DOMAIN-SUFFIX,ads.homedy.net,REJECT
# [hostvn.net]
DOMAIN-SUFFIX,ema.hostvn.net,REJECT
# [hotngay.vn]
DOMAIN-SUFFIX,game-static.hotngay.vn,REJECT
DOMAIN-SUFFIX,game.hotngay.vn,REJECT
DOMAIN-SUFFIX,hotngay.vn,REJECT
# [hqq.to]
DOMAIN-SUFFIX,hqq.to,REJECT
# [hstatic.net]
DOMAIN-SUFFIX,app.hstatic.net,REJECT
DOMAIN-SUFFIX,stats.hstatic.net,REJECT
# [hub-js.com]
DOMAIN-SUFFIX,analytics.hub-js.com,REJECT
DOMAIN-SUFFIX,marketing.hub-js.com,REJECT
# [hubs.vn]
DOMAIN-SUFFIX,ads-admin.hubs.vn,REJECT
DOMAIN-SUFFIX,hubs.vn,REJECT
DOMAIN-SUFFIX,mautic.hubs.vn,REJECT
DOMAIN-SUFFIX,tracking.hubs.vn,REJECT
# [iads.vision]
DOMAIN-SUFFIX,iads.vision,REJECT
# [icsc.vn]
DOMAIN-SUFFIX,icsc.vn,REJECT
DOMAIN-SUFFIX,mautic.icsc.vn,REJECT
# [ictnews.vn]
DOMAIN-SUFFIX,ads.ictnews.vn,REJECT
# [imacdn.com]
DOMAIN-SUFFIX,ff.imacdn.com,REJECT
DOMAIN-SUFFIX,imacdn.com,REJECT
DOMAIN-SUFFIX,sponsor.imacdn.com,REJECT
# [imad24.com]
DOMAIN-SUFFIX,imad24.com,REJECT
# [imgcdnbet.com]
DOMAIN-SUFFIX,imgcdnbet.com,REJECT
# [imgur.com]
DOMAIN-SUFFIX,imgur.com,REJECT
# [immaculate-suspect.com]
DOMAIN-SUFFIX,immaculate-suspect.com,REJECT
# [inetgroup.vn]
DOMAIN-SUFFIX,ads.inetgroup.vn,REJECT
# [infonet.vn]
DOMAIN-SUFFIX,log.infonet.vn,REJECT
# [innocom.vn]
DOMAIN-SUFFIX,pixel.innocom.vn,REJECT
# [ioe.vn]
DOMAIN-SUFFIX,advzone.ioe.vn,REJECT
# [isvn.space]
DOMAIN-SUFFIX,sv.isvn.space,REJECT
# [itim.vn]
DOMAIN-SUFFIX,itim.vn,REJECT
DOMAIN-SUFFIX,spell.itim.vn,REJECT
# [jagodo.vn]
DOMAIN-SUFFIX,jagodo.vn,REJECT
DOMAIN-SUFFIX,mautic.jagodo.vn,REJECT
# [jamstackvietnam.com]
DOMAIN-SUFFIX,analytics.jamstackvietnam.com,REJECT
# [japo.vn]
DOMAIN-SUFFIX,japo.vn,REJECT
DOMAIN-SUFFIX,qc.japo.vn,REJECT
# [javbest.cc]
DOMAIN-SUFFIX,javbest.cc,REJECT
# [jeoway.com]
DOMAIN-SUFFIX,analytics.jeoway.com,REJECT
DOMAIN-SUFFIX,jeoway.com,REJECT
DOMAIN-SUFFIX,platform.jeoway.com,REJECT
DOMAIN-SUFFIX,www.jeoway.com,REJECT
# [jeoway.net]
DOMAIN-SUFFIX,app2.jeoway.net,REJECT
DOMAIN-SUFFIX,jana1.jeoway.net,REJECT
# [joboko.com]
DOMAIN-SUFFIX,xads.joboko.com,REJECT
DOMAIN-SUFFIX,xmadsapi.joboko.com,REJECT
# [jsdelivr.net]
DOMAIN-SUFFIX,cdn.jsdelivr.net,REJECT
# [jun8899.me]
DOMAIN-SUFFIX,jun8899.me,REJECT
# [kabbmedia.com]
DOMAIN-SUFFIX,ads.kabbmedia.com,REJECT
DOMAIN-SUFFIX,delivery.kabbmedia.com,REJECT
DOMAIN-SUFFIX,images.kabbmedia.com,REJECT
DOMAIN-SUFFIX,kabbmedia.com,REJECT
# [kaka.me]
DOMAIN-SUFFIX,log.kaka.me,REJECT
# [kenh14.vn]
DOMAIN-SUFFIX,s.kenh14.vn,REJECT
# [kernh41.com]
DOMAIN-SUFFIX,ght.kernh41.com,REJECT
DOMAIN-SUFFIX,gk.kernh41.com,REJECT
DOMAIN-SUFFIX,kernh41.com,REJECT
DOMAIN-SUFFIX,static1.kernh41.com,REJECT
# [ketnoitatca.net]
DOMAIN-SUFFIX,ads.ketnoitatca.net,REJECT
# [ketquaxosotoancau.org]
DOMAIN-SUFFIX,ketquaxosotoancau.org,REJECT
DOMAIN-SUFFIX,www.ketquaxosotoancau.org,REJECT
# [kiemsat.vn]
DOMAIN-SUFFIX,ads.kiemsat.vn,REJECT
# [kinhtedothi.vn]
DOMAIN-SUFFIX,logging.kinhtedothi.vn,REJECT
# [kinhtedouong.vn]
DOMAIN-SUFFIX,log.kinhtedouong.vn,REJECT
# [kiotviet.vn]
DOMAIN-SUFFIX,kv-analytics.kiotviet.vn,REJECT
# [klick.vn]
DOMAIN-SUFFIX,adv.klick.vn,REJECT
DOMAIN-SUFFIX,demo.klick.vn,REJECT
DOMAIN-SUFFIX,euro.klick.vn,REJECT
DOMAIN-SUFFIX,klick.vn,REJECT
DOMAIN-SUFFIX,qc.klick.vn,REJECT
DOMAIN-SUFFIX,text1.klick.vn,REJECT
DOMAIN-SUFFIX,wakeup.klick.vn,REJECT
DOMAIN-SUFFIX,wakeup247.klick.vn,REJECT
DOMAIN-SUFFIX,www.klick.vn,REJECT
# [kone.vn]
DOMAIN-SUFFIX,smetrics.kone.vn,REJECT
# [kplus.vn]
DOMAIN-SUFFIX,webstag.kplus.vn,REJECT
# [kqbd88.com]
DOMAIN-SUFFIX,kqbd88.com,REJECT
DOMAIN-SUFFIX,qc.kqbd88.com,REJECT
# [ku42hjr2e.com]
DOMAIN-SUFFIX,ku42hjr2e.com,REJECT
# [kul.vn]
DOMAIN-SUFFIX,adx.kul.vn,REJECT
# [kvsadman.com]
DOMAIN-SUFFIX,kvsadman.com,REJECT
# [kyna.vn]
DOMAIN-SUFFIX,track.kyna.vn,REJECT
DOMAIN-SUFFIX,widget.kyna.vn,REJECT
# [kz2oq0xm6ie7gn5dkswlpv6mfgci8yoe3xlqp12gjotp5fdjxs5ckztb8rzn.codes]
DOMAIN-SUFFIX,kz2oq0xm6ie7gn5dkswlpv6mfgci8yoe3xlqp12gjotp5fdjxs5ckztb8rzn.codes,REJECT
# [ladipage.com]
DOMAIN-SUFFIX,a.ladipage.com,REJECT
# [lag.vn]
DOMAIN-SUFFIX,adserver.lag.vn,REJECT
# [lamchame.vn]
DOMAIN-SUFFIX,ads.lamchame.vn,REJECT
# [lamthong.net]
DOMAIN-SUFFIX,lamthong.net,REJECT
# [landingpagelagi.vn]
DOMAIN-SUFFIX,landingpagelagi.vn,REJECT
# [laodongnghean.vn]
DOMAIN-SUFFIX,ads.laodongnghean.vn,REJECT
# [lavamedia.vn]
DOMAIN-SUFFIX,delivery.lavamedia.vn,REJECT
DOMAIN-SUFFIX,delivery1.lavamedia.vn,REJECT
DOMAIN-SUFFIX,lavamedia.vn,REJECT
DOMAIN-SUFFIX,pub.lavamedia.vn,REJECT
# [lavanetwork.net]
DOMAIN-SUFFIX,ad.lavanetwork.net,REJECT
DOMAIN-SUFFIX,admin.lavanetwork.net,REJECT
DOMAIN-SUFFIX,banner.lavanetwork.net,REJECT
DOMAIN-SUFFIX,creatives.lavanetwork.net,REJECT
DOMAIN-SUFFIX,delivery.lavanetwork.net,REJECT
DOMAIN-SUFFIX,delivery1.lavanetwork.net,REJECT
DOMAIN-SUFFIX,img.lavanetwork.net,REJECT
DOMAIN-SUFFIX,lavanetwork.net,REJECT
DOMAIN-SUFFIX,libs.lavanetwork.net,REJECT
DOMAIN-SUFFIX,log.lavanetwork.net,REJECT
DOMAIN-SUFFIX,pub.lavanetwork.net,REJECT
DOMAIN-SUFFIX,revive.lavanetwork.net,REJECT
DOMAIN-SUFFIX,video.lavanetwork.net,REJECT
DOMAIN-SUFFIX,www.lavanetwork.net,REJECT
# [lichviet.org]
DOMAIN-SUFFIX,log.lichviet.org,REJECT
# [linksht.online]
DOMAIN-SUFFIX,aff2.linksht.online,REJECT
# [lotus.vn]
DOMAIN-SUFFIX,lg.lotus.vn,REJECT
# [lsvn.vn]
DOMAIN-SUFFIX,delivery.lsvn.vn,REJECT
DOMAIN-SUFFIX,tracking.lsvn.vn,REJECT
# [m6pz5h8qi18jq1s7hjkytxn7sjc0zpxw5gks3vyk8dcxs2cstjgdxkp7t1eb.me]
DOMAIN-SUFFIX,m6pz5h8qi18jq1s7hjkytxn7sjc0zpxw5gks3vyk8dcxs2cstjgdxkp7t1eb.me,REJECT
# [magsrv.com]
DOMAIN-SUFFIX,magsrv.com,REJECT
# [markettimes.vn]
DOMAIN-SUFFIX,ads.markettimes.vn,REJECT
# [marry.vn]
DOMAIN-SUFFIX,ads.marry.vn,REJECT
# [masoffer.net]
DOMAIN-SUFFIX,static.masoffer.net,REJECT
# [max88.com]
DOMAIN-SUFFIX,max88.com,REJECT
# [mclick.mobi]
DOMAIN-SUFFIX,aff.mclick.mobi,REJECT
DOMAIN-SUFFIX,cdn.mclick.mobi,REJECT
DOMAIN-SUFFIX,cloudfront.mclick.mobi,REJECT
DOMAIN-SUFFIX,cpa-tracking.mclick.mobi,REJECT
DOMAIN-SUFFIX,down.us2.mclick.mobi,REJECT
DOMAIN-SUFFIX,down140.mclick.mobi,REJECT
DOMAIN-SUFFIX,down141.mclick.mobi,REJECT
DOMAIN-SUFFIX,download.mclick.mobi,REJECT
DOMAIN-SUFFIX,mclick.mobi,REJECT
DOMAIN-SUFFIX,script.mclick.mobi,REJECT
DOMAIN-SUFFIX,static.download.mclick.mobi,REJECT
DOMAIN-SUFFIX,track.mclick.mobi,REJECT
DOMAIN-SUFFIX,www.mclick.mobi,REJECT
# [media.net]
DOMAIN-SUFFIX,media.net,REJECT
DOMAIN-SUFFIX,static.media.net,REJECT
# [mediacdn.vn]
DOMAIN-SUFFIX,sentry.mediacdn.vn,REJECT
# [mediahub.vn]
DOMAIN-SUFFIX,report.mediahub.vn,REJECT
DOMAIN-SUFFIX,report2.mediahub.vn,REJECT
# [mediaphim.com]
DOMAIN-SUFFIX,upfile16.mediaphim.com,REJECT
# [mediaz.asia]
DOMAIN-SUFFIX,adx.mediaz.asia,REJECT
DOMAIN-SUFFIX,dsp.mediaz.asia,REJECT
DOMAIN-SUFFIX,js.mediaz.asia,REJECT
DOMAIN-SUFFIX,mediaz.asia,REJECT
DOMAIN-SUFFIX,static.mediaz.asia,REJECT
DOMAIN-SUFFIX,www.mediaz.asia,REJECT
# [mediaz.vn]
DOMAIN-SUFFIX,brief.mediaz.vn,REJECT
DOMAIN-SUFFIX,dnsbak.mediaz.vn,REJECT
DOMAIN-SUFFIX,go.mediaz.vn,REJECT
DOMAIN-SUFFIX,imc.mediaz.vn,REJECT
DOMAIN-SUFFIX,insight.mediaz.vn,REJECT
DOMAIN-SUFFIX,landing.mediaz.vn,REJECT
DOMAIN-SUFFIX,mediaz.vn,REJECT
DOMAIN-SUFFIX,nsbak.mediaz.vn,REJECT
DOMAIN-SUFFIX,offer.mediaz.vn,REJECT
DOMAIN-SUFFIX,proof.mediaz.vn,REJECT
DOMAIN-SUFFIX,report.mediaz.vn,REJECT
DOMAIN-SUFFIX,send.mediaz.vn,REJECT
DOMAIN-SUFFIX,seo.mediaz.vn,REJECT
DOMAIN-SUFFIX,tuyendung.mediaz.vn,REJECT
DOMAIN-SUFFIX,viral.mediaz.vn,REJECT
DOMAIN-SUFFIX,wallet.mediaz.vn,REJECT
DOMAIN-SUFFIX,www.mediaz.vn,REJECT
DOMAIN-SUFFIX,zalo-ads.mediaz.vn,REJECT
# [mediazcorp.com]
DOMAIN-SUFFIX,mediazcorp.com,REJECT
DOMAIN-SUFFIX,www.mediazcorp.com,REJECT
# [mekongasean.vn]
DOMAIN-SUFFIX,log.mekongasean.vn,REJECT
# [mepuzz.com]
DOMAIN-SUFFIX,mepuzz.com,REJECT
DOMAIN-SUFFIX,static.mepuzz.com,REJECT
DOMAIN-SUFFIX,www.mepuzz.com,REJECT
# [meta.vn]
DOMAIN-SUFFIX,meta.vn,REJECT
DOMAIN-SUFFIX,tracking.meta.vn,REJECT
# [metaconex.io]
DOMAIN-SUFFIX,metaconex.io,REJECT
DOMAIN-SUFFIX,pub.metaconex.io,REJECT
DOMAIN-SUFFIX,www.metaconex.io,REJECT
# [metric.vn]
DOMAIN-SUFFIX,logv3.metric.vn,REJECT
# [metu.vn]
DOMAIN-SUFFIX,menu.metu.vn,REJECT
# [mhsolution.vn]
DOMAIN-SUFFIX,mhsolution.vn,REJECT
DOMAIN-SUFFIX,qc.mhsolution.vn,REJECT
# [microad.vn]
DOMAIN-SUFFIX,microad.vn,REJECT
DOMAIN-SUFFIX,www.microad.vn,REJECT
# [midgetmaying.com]
DOMAIN-SUFFIX,midgetmaying.com,REJECT
# [mobiedu.vn]
DOMAIN-SUFFIX,analytics-cds.mobiedu.vn,REJECT
DOMAIN-SUFFIX,analytics.mobiedu.vn,REJECT
# [mobifone.vn]
DOMAIN-SUFFIX,adhub.mobifone.vn,REJECT
DOMAIN-SUFFIX,banner.etargeting.mobifone.vn,REJECT
# [mobilead.vn]
DOMAIN-SUFFIX,dev.mobilead.vn,REJECT
DOMAIN-SUFFIX,mobilead.vn,REJECT
# [mobio.vn]
DOMAIN-SUFFIX,api.mobio.vn,REJECT
DOMAIN-SUFFIX,app.mobio.vn,REJECT
DOMAIN-SUFFIX,loind.mobio.vn,REJECT
DOMAIN-SUFFIX,mobio.vn,REJECT
DOMAIN-SUFFIX,www.mobio.vn,REJECT
# [modestsunf.com]
DOMAIN-SUFFIX,dest.modestsunf.com,REJECT
DOMAIN-SUFFIX,modestsunf.com,REJECT
# [mona.host]
DOMAIN-SUFFIX,web-analytics.mona.host,REJECT
# [moneycat.vn]
DOMAIN-SUFFIX,analytics.moneycat.vn,REJECT
# [moneyoyo.com]
DOMAIN-SUFFIX,sdk.moneyoyo.com,REJECT
# [moneyoyo.org]
DOMAIN-SUFFIX,api.moneyoyo.org,REJECT
# [motgame.vn]
DOMAIN-SUFFIX,openx.motgame.vn,REJECT
# [motphimqq.pro]
DOMAIN-SUFFIX,motphimqq.pro,REJECT
# [mpcdn.top]
DOMAIN-SUFFIX,ax.mpcdn.top,REJECT
# [msdigital.vn]
DOMAIN-SUFFIX,ads.msdigital.vn,REJECT
# [muaban.net]
DOMAIN-SUFFIX,adserver.muaban.net,REJECT
# [mvot.vn]
DOMAIN-SUFFIX,static.mvot.vn,REJECT
# [mxhnkn.pro]
DOMAIN-SUFFIX,ads.mxhnkn.pro,REJECT
DOMAIN-SUFFIX,mxhnkn.pro,REJECT
# [myad.vn]
DOMAIN-SUFFIX,adscare.myad.vn,REJECT
DOMAIN-SUFFIX,cdn.myad.vn,REJECT
DOMAIN-SUFFIX,dmp.myad.vn,REJECT
DOMAIN-SUFFIX,myad.vn,REJECT
DOMAIN-SUFFIX,www.myad.vn,REJECT
# [mytvnet.vn]
DOMAIN-SUFFIX,apilog.mytvnet.vn,REJECT
DOMAIN-SUFFIX,apilogduration.mytvnet.vn,REJECT
DOMAIN-SUFFIX,mytvnet.vn,REJECT
# [n7e4t5trg0u3yegn8szj9c8xjz5wf8szcj2a5h9dzxjs50salczs8azls0zm.com]
DOMAIN-SUFFIX,n7e4t5trg0u3yegn8szj9c8xjz5wf8szcj2a5h9dzxjs50salczs8azls0zm.com,REJECT
# [nanda.vn]
DOMAIN-SUFFIX,ai.nanda.vn,REJECT
DOMAIN-SUFFIX,analytics.nanda.vn,REJECT
DOMAIN-SUFFIX,cdn.nanda.vn,REJECT
DOMAIN-SUFFIX,lg.nanda.vn,REJECT
DOMAIN-SUFFIX,nanda.vn,REJECT
DOMAIN-SUFFIX,static.nanda.vn,REJECT
# [native-ad.net]
DOMAIN-SUFFIX,ad.native-ad.net,REJECT
DOMAIN-SUFFIX,beauty.native-ad.net,REJECT
DOMAIN-SUFFIX,code.native-ad.net,REJECT
DOMAIN-SUFFIX,gluco.native-ad.net,REJECT
DOMAIN-SUFFIX,native-ad.net,REJECT
DOMAIN-SUFFIX,tags.native-ad.net,REJECT
DOMAIN-SUFFIX,vena.native-ad.net,REJECT
# [nct.vn]
DOMAIN-SUFFIX,api.nas.nct.vn,REJECT
DOMAIN-SUFFIX,apinas.nct.vn,REJECT
DOMAIN-SUFFIX,nct2-logging.nct.vn,REJECT
# [net-solutions.vn]
DOMAIN-SUFFIX,upl.net-solutions.vn,REJECT
# [net.vn]
DOMAIN-SUFFIX,ads.fptplay.net.vn,REJECT
DOMAIN-SUFFIX,adtima.net.vn,REJECT
DOMAIN-SUFFIX,adx.hoanggia.net.vn,REJECT
DOMAIN-SUFFIX,client.vads.net.vn,REJECT
DOMAIN-SUFFIX,log-tamnhin.kienthuc.net.vn,REJECT
DOMAIN-SUFFIX,log.giaoduc.net.vn,REJECT
DOMAIN-SUFFIX,log.kienthuc.net.vn,REJECT
DOMAIN-SUFFIX,log.vads.net.vn,REJECT
DOMAIN-SUFFIX,logv2.kienthuc.net.vn,REJECT
DOMAIN-SUFFIX,vads.net.vn,REJECT
DOMAIN-SUFFIX,vietnamdaily-log.kienthuc.net.vn,REJECT
DOMAIN-SUFFIX,www.vads.net.vn,REJECT
# [net88.in]
DOMAIN-SUFFIX,net88.in,REJECT
# [nextsmarty.com]
DOMAIN-SUFFIX,nct1.logging.nextsmarty.com,REJECT
# [ngaynay.vn]
DOMAIN-SUFFIX,log.ngaynay.vn,REJECT
# [nghenhinvietnam.vn]
DOMAIN-SUFFIX,ads.nghenhinvietnam.vn,REJECT
# [nguoiduatin.vn]
DOMAIN-SUFFIX,ads.nguoiduatin.vn,REJECT
# [nguoimuanha.vn]
DOMAIN-SUFFIX,log.nguoimuanha.vn,REJECT
# [nhadatmoi.net]
DOMAIN-SUFFIX,ads.nhadatmoi.net,REJECT
# [nhandan.vn]
DOMAIN-SUFFIX,log-en.nhandan.vn,REJECT
DOMAIN-SUFFIX,log.nhandan.vn,REJECT
# [nhanhoa.com]
DOMAIN-SUFFIX,liveonline.nhanhoa.com,REJECT
# [nhanlucnganhluat.vn]
DOMAIN-SUFFIX,elink.nhanlucnganhluat.vn,REJECT
# [nhattao.com]
DOMAIN-SUFFIX,analytics.nhattao.com,REJECT
# [nhipcaudautu.vn]
DOMAIN-SUFFIX,adsgo.nhipcaudautu.vn,REJECT
DOMAIN-SUFFIX,log.nhipcaudautu.vn,REJECT
# [nixcdn.com]
DOMAIN-SUFFIX,log4x.nixcdn.com,REJECT
DOMAIN-SUFFIX,nixcdn.com,REJECT
DOMAIN-SUFFIX,stc-nas.nixcdn.com,REJECT
DOMAIN-SUFFIX,stc.nas.nixcdn.com,REJECT
# [novanet.vn]
DOMAIN-SUFFIX,admin.novanet.vn,REJECT
DOMAIN-SUFFIX,ads.novanet.vn,REJECT
DOMAIN-SUFFIX,analytics.novanet.vn,REJECT
DOMAIN-SUFFIX,banner.novanet.vn,REJECT
DOMAIN-SUFFIX,click.novanet.vn,REJECT
DOMAIN-SUFFIX,cp.novanet.vn,REJECT
DOMAIN-SUFFIX,cpcclick.novanet.vn,REJECT
DOMAIN-SUFFIX,cpm.novanet.vn,REJECT
DOMAIN-SUFFIX,f.novanet.vn,REJECT
DOMAIN-SUFFIX,f2.novanet.vn,REJECT
DOMAIN-SUFFIX,file.novanet.vn,REJECT
DOMAIN-SUFFIX,landingpage.novanet.vn,REJECT
DOMAIN-SUFFIX,lp.novanet.vn,REJECT
DOMAIN-SUFFIX,mobile.novanet.vn,REJECT
DOMAIN-SUFFIX,novanet.vn,REJECT
DOMAIN-SUFFIX,rnd.novanet.vn,REJECT
DOMAIN-SUFFIX,script.novanet.vn,REJECT
DOMAIN-SUFFIX,static.novanet.vn,REJECT
DOMAIN-SUFFIX,www.novanet.vn,REJECT
# [novaon.asia]
DOMAIN-SUFFIX,cms.novaon.asia,REJECT
DOMAIN-SUFFIX,crowd.novaon.asia,REJECT
DOMAIN-SUFFIX,erp.novaon.asia,REJECT
DOMAIN-SUFFIX,erp2.novaon.asia,REJECT
DOMAIN-SUFFIX,hrm.novaon.asia,REJECT
DOMAIN-SUFFIX,hrm2.novaon.asia,REJECT
DOMAIN-SUFFIX,jira.novaon.asia,REJECT
DOMAIN-SUFFIX,novaon.asia,REJECT
DOMAIN-SUFFIX,phi.novaon.asia,REJECT
DOMAIN-SUFFIX,report.novaon.asia,REJECT
DOMAIN-SUFFIX,www.novaon.asia,REJECT
# [novaon.vn]
DOMAIN-SUFFIX,novaon.vn,REJECT
DOMAIN-SUFFIX,www.novaon.vn,REJECT
# [novaonads.com]
DOMAIN-SUFFIX,novaonads.com,REJECT
DOMAIN-SUFFIX,www.novaonads.com,REJECT
# [novaonx.com]
DOMAIN-SUFFIX,api-ldp.novaonx.com,REJECT
DOMAIN-SUFFIX,chatbot-staging.novaonx.com,REJECT
DOMAIN-SUFFIX,chatbot-tracking.novaonx.com,REJECT
DOMAIN-SUFFIX,chatbot.novaonx.com,REJECT
DOMAIN-SUFFIX,chatbotthoitrang.novaonx.com,REJECT
DOMAIN-SUFFIX,chatbottudong.novaonx.com,REJECT
DOMAIN-SUFFIX,landingpage.novaonx.com,REJECT
DOMAIN-SUFFIX,novaonx.com,REJECT
DOMAIN-SUFFIX,pub-dev.novaonx.com,REJECT
DOMAIN-SUFFIX,staging.novaonx.com,REJECT
DOMAIN-SUFFIX,www.novaonx.com,REJECT
# [ntdvn.com]
DOMAIN-SUFFIX,counter.ntdvn.com,REJECT
# [nvcms.net]
DOMAIN-SUFFIX,traffic.nvcms.net,REJECT
# [ohchat.net]
DOMAIN-SUFFIX,app.ohchat.net,REJECT
DOMAIN-SUFFIX,ohchat.net,REJECT
DOMAIN-SUFFIX,www.ohchat.net,REJECT
# [oncustomer.asia]
DOMAIN-SUFFIX,api-internal-dev.oncustomer.asia,REJECT
DOMAIN-SUFFIX,api-internal.oncustomer.asia,REJECT
DOMAIN-SUFFIX,app.oncustomer.asia,REJECT
DOMAIN-SUFFIX,beta.oncustomer.asia,REJECT
DOMAIN-SUFFIX,hook.oncustomer.asia,REJECT
DOMAIN-SUFFIX,live-api.oncustomer.asia,REJECT
DOMAIN-SUFFIX,livechat.oncustomer.asia,REJECT
DOMAIN-SUFFIX,oncustomer.asia,REJECT
DOMAIN-SUFFIX,push.oncustomer.asia,REJECT
DOMAIN-SUFFIX,reports-api.oncustomer.asia,REJECT
DOMAIN-SUFFIX,webbot.oncustomer.asia,REJECT
DOMAIN-SUFFIX,widget-1.oncustomer.asia,REJECT
DOMAIN-SUFFIX,widget-2.oncustomer.asia,REJECT
DOMAIN-SUFFIX,widget.oncustomer.asia,REJECT
DOMAIN-SUFFIX,www.oncustomer.asia,REJECT
# [onfluencer.net]
DOMAIN-SUFFIX,alpha.onfluencer.net,REJECT
DOMAIN-SUFFIX,analytics.onfluencer.net,REJECT
DOMAIN-SUFFIX,beta.onfluencer.net,REJECT
DOMAIN-SUFFIX,hub.onfluencer.net,REJECT
DOMAIN-SUFFIX,iosalpha.onfluencer.net,REJECT
DOMAIN-SUFFIX,l.onfluencer.net,REJECT
DOMAIN-SUFFIX,onfluencer.net,REJECT
DOMAIN-SUFFIX,tracking.onfluencer.net,REJECT
DOMAIN-SUFFIX,www.onfluencer.net,REJECT
# [onmarketer.net]
DOMAIN-SUFFIX,beta.onmarketer.net,REJECT
DOMAIN-SUFFIX,hub.onmarketer.net,REJECT
DOMAIN-SUFFIX,onmarketer.net,REJECT
DOMAIN-SUFFIX,www.onmarketer.net,REJECT
# [opencoccoc.com]
DOMAIN-SUFFIX,ccxj.opencoccoc.com,REJECT
DOMAIN-SUFFIX,ccxp.opencoccoc.com,REJECT
DOMAIN-SUFFIX,occi.opencoccoc.com,REJECT
DOMAIN-SUFFIX,sr.opencoccoc.com,REJECT
# [opencps.vn]
DOMAIN-SUFFIX,thongke.opencps.vn,REJECT
# [openfpcdn.io]
DOMAIN-SUFFIX,openfpcdn.io,REJECT
# [orbsrv.com]
DOMAIN-SUFFIX,orbsrv.com,REJECT
# [org.vn]
DOMAIN-SUFFIX,ad.org.vn,REJECT
DOMAIN-SUFFIX,adv.baovemoitruong.org.vn,REJECT
DOMAIN-SUFFIX,cdn.serving.ad.org.vn,REJECT
DOMAIN-SUFFIX,log-dttc.sggp.org.vn,REJECT
DOMAIN-SUFFIX,log-en.sggp.org.vn,REJECT
DOMAIN-SUFFIX,log.sggp.org.vn,REJECT
DOMAIN-SUFFIX,member.ad.org.vn,REJECT
DOMAIN-SUFFIX,serving.ad.org.vn,REJECT
DOMAIN-SUFFIX,static.ad.org.vn,REJECT
DOMAIN-SUFFIX,www.ad.org.vn,REJECT
# [osd.vn]
DOMAIN-SUFFIX,stats.osd.vn,REJECT
# [oursty.com]
DOMAIN-SUFFIX,oursty.com,REJECT
# [overseagyassa.com]
DOMAIN-SUFFIX,overseagyassa.com,REJECT
# [ovp.vn]
DOMAIN-SUFFIX,collect.ovp.vn,REJECT
DOMAIN-SUFFIX,fbuser.ovp.vn,REJECT
# [pancake.vn]
DOMAIN-SUFFIX,analytics.pancake.vn,REJECT
# [pangle-b.io]
DOMAIN-SUFFIX,pangle-b.io,REJECT
# [pangle.io]
DOMAIN-SUFFIX,pangle.io,REJECT
# [pasjcutadak.com]
DOMAIN-SUFFIX,pasjcutadak.com,REJECT
# [petrotimes.vn]
DOMAIN-SUFFIX,stats.petrotimes.vn,REJECT
# [phanquang.vn]
DOMAIN-SUFFIX,click.phanquang.vn,REJECT
DOMAIN-SUFFIX,phanquang.vn,REJECT
DOMAIN-SUFFIX,quangcao.phanquang.vn,REJECT
# [philacct.com]
DOMAIN-SUFFIX,fgp.philacct.com,REJECT
DOMAIN-SUFFIX,philacct.com,REJECT
DOMAIN-SUFFIX,static.philacct.com,REJECT
# [phimmoizz.net]
DOMAIN-SUFFIX,clientinfo.phimmoizz.net,REJECT
# [phukienthoitranggiare.com]
DOMAIN-SUFFIX,asg.phukienthoitranggiare.com,REJECT
DOMAIN-SUFFIX,phukienthoitranggiare.com,REJECT
DOMAIN-SUFFIX,www.phukienthoitranggiare.com,REJECT
# [phunuadong.vn]
DOMAIN-SUFFIX,adx.phunuadong.vn,REJECT
DOMAIN-SUFFIX,tracking.phunuadong.vn,REJECT
# [phunusuckhoe.vn]
DOMAIN-SUFFIX,adm.phunusuckhoe.vn,REJECT
DOMAIN-SUFFIX,admin.phunusuckhoe.vn,REJECT
DOMAIN-SUFFIX,adms.phunusuckhoe.vn,REJECT
DOMAIN-SUFFIX,ads.phunusuckhoe.vn,REJECT
DOMAIN-SUFFIX,tracker.phunusuckhoe.vn,REJECT
# [phunuvagiadinh.vn]
DOMAIN-SUFFIX,adm.phunuvagiadinh.vn,REJECT
DOMAIN-SUFFIX,ads.phunuvagiadinh.vn,REJECT
DOMAIN-SUFFIX,tracker.phunuvagiadinh.vn,REJECT
# [phunuxuavanay.vn]
DOMAIN-SUFFIX,ad.phunuxuavanay.vn,REJECT
DOMAIN-SUFFIX,phunuxuavanay.vn,REJECT
# [pinetech.vn]
DOMAIN-SUFFIX,demo.pinetech.vn,REJECT
DOMAIN-SUFFIX,pinetech.vn,REJECT
DOMAIN-SUFFIX,www.pinetech.vn,REJECT
# [pinterest.com]
DOMAIN-SUFFIX,ads.pinterest.com,REJECT
DOMAIN-SUFFIX,analytics.pinterest.com,REJECT
# [playfun.vn]
DOMAIN-SUFFIX,ads-api.playfun.vn,REJECT
DOMAIN-SUFFIX,playfun.vn,REJECT
# [plo.vn]
DOMAIN-SUFFIX,log.plo.vn,REJECT
# [poasauwhoothy.net]
DOMAIN-SUFFIX,poasauwhoothy.net,REJECT
# [polyad.net]
DOMAIN-SUFFIX,core.polyad.net,REJECT
DOMAIN-SUFFIX,cp.polyad.net,REJECT
DOMAIN-SUFFIX,cpx.polyad.net,REJECT
DOMAIN-SUFFIX,ds.polyad.net,REJECT
DOMAIN-SUFFIX,dst.polyad.net,REJECT
DOMAIN-SUFFIX,dt.polyad.net,REJECT
DOMAIN-SUFFIX,go.polyad.net,REJECT
DOMAIN-SUFFIX,html.polyad.net,REJECT
DOMAIN-SUFFIX,img.polyad.net,REJECT
DOMAIN-SUFFIX,polyad.net,REJECT
DOMAIN-SUFFIX,st.core.polyad.net,REJECT
DOMAIN-SUFFIX,st.html.polyad.net,REJECT
DOMAIN-SUFFIX,st.polyad.net,REJECT
# [popsww.com]
DOMAIN-SUFFIX,track.popsww.com,REJECT
# [proadscdn.com]
DOMAIN-SUFFIX,adx.proadscdn.com,REJECT
DOMAIN-SUFFIX,cdn.proadscdn.com,REJECT
DOMAIN-SUFFIX,cdn5.proadscdn.com,REJECT
DOMAIN-SUFFIX,media.proadscdn.com,REJECT
DOMAIN-SUFFIX,opt.proadscdn.com,REJECT
DOMAIN-SUFFIX,owl.proadscdn.com,REJECT
DOMAIN-SUFFIX,proadscdn.com,REJECT
DOMAIN-SUFFIX,script.proadscdn.com,REJECT
DOMAIN-SUFFIX,www.proadscdn.com,REJECT
# [proxyme.link]
DOMAIN-SUFFIX,analytic.proxyme.link,REJECT
# [psugheeghuli.net]
DOMAIN-SUFFIX,psugheeghuli.net,REJECT
# [pubmatic.com]
DOMAIN-SUFFIX,pubmatic.com,REJECT
# [pushdi.com]
DOMAIN-SUFFIX,api.pushdi.com,REJECT
DOMAIN-SUFFIX,pushdi.com,REJECT
DOMAIN-SUFFIX,sdk.pushdi.com,REJECT
# [pushdy.com]
DOMAIN-SUFFIX,cdn.pushdy.com,REJECT
DOMAIN-SUFFIX,pushdy.com,REJECT
DOMAIN-SUFFIX,www.pushdy.com,REJECT
# [pushdy.vn]
DOMAIN-SUFFIX,pushdy.vn,REJECT
DOMAIN-SUFFIX,www.pushdy.vn,REJECT
# [pushtimize.com]
DOMAIN-SUFFIX,adv.pushtimize.com,REJECT
DOMAIN-SUFFIX,cdn01.pushtimize.com,REJECT
DOMAIN-SUFFIX,feed.pushtimize.com,REJECT
DOMAIN-SUFFIX,pushtimize.com,REJECT
DOMAIN-SUFFIX,www.pushtimize.com,REJECT
# [q2h0x5l7gj8xdm5wdx8ht5szd4jw8nzq5klt8sr9sk2zjg6mtk0q8xzi0i9z.me]
DOMAIN-SUFFIX,q2h0x5l7gj8xdm5wdx8ht5szd4jw8nzq5klt8sr9sk2zjg6mtk0q8xzi0i9z.me,REJECT
# [qc24h.com]
DOMAIN-SUFFIX,cdn.qc24h.com,REJECT
# [qccoccocmedia.vn]
DOMAIN-SUFFIX,qccoccocmedia.vn,REJECT
# [quangcaococcoc.vn]
DOMAIN-SUFFIX,quangcaococcoc.vn,REJECT
# [quangcaodantri.vn]
DOMAIN-SUFFIX,quangcaodantri.vn,REJECT
# [quoracdn.net]
DOMAIN-SUFFIX,quoracdn.net,REJECT
# [realclick.vn]
DOMAIN-SUFFIX,as.realclick.vn,REJECT
DOMAIN-SUFFIX,i.realclick.vn,REJECT
DOMAIN-SUFFIX,realclick.vn,REJECT
DOMAIN-SUFFIX,stats.realclick.vn,REJECT
DOMAIN-SUFFIX,www.realclick.vn,REJECT
# [rever.vn]
DOMAIN-SUFFIX,analytics.rever.vn,REJECT
# [riviu.co]
DOMAIN-SUFFIX,production-tracking.riviu.co,REJECT
# [rottencycle.com]
DOMAIN-SUFFIX,rottencycle.com,REJECT
# [rta.vn]
DOMAIN-SUFFIX,piwik.rta.vn,REJECT
# [run.app]
DOMAIN-SUFFIX,tagging-qadkfoj6ha-as.a.run.app,REJECT
# [saas-vn.network]
DOMAIN-SUFFIX,analytics.saas-vn.network,REJECT
DOMAIN-SUFFIX,congnb.analytics.saas-vn.network,REJECT
# [saigon.pro]
DOMAIN-SUFFIX,track.saigon.pro,REJECT
# [salemall.vn]
DOMAIN-SUFFIX,ads.salemall.vn,REJECT
# [sanchoikns.vn]
DOMAIN-SUFFIX,logs.sanchoikns.vn,REJECT
# [saostar.vn]
DOMAIN-SUFFIX,gtm.saostar.vn,REJECT
DOMAIN-SUFFIX,px.saostar.vn,REJECT
DOMAIN-SUFFIX,tracking.saostar.vn,REJECT
# [sapoapps.vn]
DOMAIN-SUFFIX,blogstatistics.sapoapps.vn,REJECT
DOMAIN-SUFFIX,bwstatistics.sapoapps.vn,REJECT
DOMAIN-SUFFIX,google-shopping-v2.sapoapps.vn,REJECT
DOMAIN-SUFFIX,google-shopping.sapoapps.vn,REJECT
DOMAIN-SUFFIX,googleshopping.sapoapps.vn,REJECT
DOMAIN-SUFFIX,popup.sapoapps.vn,REJECT
DOMAIN-SUFFIX,promotionbar.sapoapps.vn,REJECT
DOMAIN-SUFFIX,promotionpopup.sapoapps.vn,REJECT
DOMAIN-SUFFIX,sapoapps.vn,REJECT
DOMAIN-SUFFIX,statistic-blog-v2.sapoapps.vn,REJECT
# [sbbanner.com]
DOMAIN-SUFFIX,sbbanner.com,REJECT
DOMAIN-SUFFIX,www.sbbanner.com,REJECT
# [sendo.vn]
DOMAIN-SUFFIX,track.sendo.vn,REJECT
# [sentry-cdn.com]
DOMAIN-SUFFIX,browser.sentry-cdn.com,REJECT
# [senvangvn.com]
DOMAIN-SUFFIX,delivery.senvangvn.com,REJECT
# [seovietnam.pro]
DOMAIN-SUFFIX,ads.seovietnam.pro,REJECT
DOMAIN-SUFFIX,seovietnam.pro,REJECT
# [serverhub.vn]
DOMAIN-SUFFIX,mautic.serverhub.vn,REJECT
DOMAIN-SUFFIX,serverhub.vn,REJECT
# [sexyland.vn]
DOMAIN-SUFFIX,ads.sexyland.vn,REJECT
# [shac.vn]
DOMAIN-SUFFIX,matomo.shac.vn,REJECT
# [sharks.vn]
DOMAIN-SUFFIX,sharks.vn,REJECT
# [shopee.vn]
DOMAIN-SUFFIX,log-collector.shopee.vn,REJECT
DOMAIN-SUFFIX,s.shopee.vn,REJECT
DOMAIN-SUFFIX,userstats.shopee.vn,REJECT
# [showbiref.pro]
DOMAIN-SUFFIX,showbiref.pro,REJECT
# [slimads.vn]
DOMAIN-SUFFIX,app.slimads.vn,REJECT
DOMAIN-SUFFIX,slimads.vn,REJECT
DOMAIN-SUFFIX,www.slimads.vn,REJECT
# [smartadserver.com]
DOMAIN-SUFFIX,smartadserver.com,REJECT
# [smobgame.com]
DOMAIN-SUFFIX,tracking-web.smobgame.com,REJECT
# [smoney.vn]
DOMAIN-SUFFIX,log.smoney.vn,REJECT
# [soc88.com]
DOMAIN-SUFFIX,soc88.com,REJECT
# [soha.vn]
DOMAIN-SUFFIX,s.soha.vn,REJECT
# [sohatv.vn]
DOMAIN-SUFFIX,adminplayer.sohatv.vn,REJECT
DOMAIN-SUFFIX,analytics.sohatv.vn,REJECT
DOMAIN-SUFFIX,api-logdev.sohatv.vn,REJECT
# [songmoi.vn]
DOMAIN-SUFFIX,ads.songmoi.vn,REJECT
# [sothuchi.vn]
DOMAIN-SUFFIX,admin.sothuchi.vn,REJECT
# [sourcetobin.com]
DOMAIN-SUFFIX,sourcetobin.com,REJECT
DOMAIN-SUFFIX,static.sourcetobin.com,REJECT
# [starseed.fr]
DOMAIN-SUFFIX,cdn.starseed.fr,REJECT
DOMAIN-SUFFIX,log.starseed.fr,REJECT
DOMAIN-SUFFIX,starseed.fr,REJECT
# [starzd.com]
DOMAIN-SUFFIX,starzd.com,REJECT
# [staticscdn.net]
DOMAIN-SUFFIX,iads.staticscdn.net,REJECT
DOMAIN-SUFFIX,staticscdn.net,REJECT
# [storageimagedisplay.com]
DOMAIN-SUFFIX,cdn.storageimagedisplay.com,REJECT
# [sts.vn]
DOMAIN-SUFFIX,mautic.sts.vn,REJECT
# [su6t2a0v1cbj6fu8o2cjdo1dx0oxdm6kgl6f7zdjxt6aqxjlwrt7cu2r5g2d.me]
DOMAIN-SUFFIX,su6t2a0v1cbj6fu8o2cjdo1dx0oxdm6kgl6f7zdjxt6aqxjlwrt7cu2r5g2d.me,REJECT
# [subiz-cdn.com]
DOMAIN-SUFFIX,public-gcs.subiz-cdn.com,REJECT
DOMAIN-SUFFIX,vcdn.subiz-cdn.com,REJECT
# [subiz.com]
DOMAIN-SUFFIX,apiv4.subiz.com,REJECT
DOMAIN-SUFFIX,static.subiz.com,REJECT
DOMAIN-SUFFIX,widget.subiz.com,REJECT
DOMAIN-SUFFIX,widgetv4.subiz.com,REJECT
# [subiz.net]
DOMAIN-SUFFIX,api.subiz.net,REJECT
DOMAIN-SUFFIX,widget.subiz.net,REJECT
# [subiz.xyz]
DOMAIN-SUFFIX,api.subiz.xyz,REJECT
DOMAIN-SUFFIX,subiz.xyz,REJECT
DOMAIN-SUFFIX,widget.subiz.xyz,REJECT
# [sudo.vn]
DOMAIN-SUFFIX,proof.sudo.vn,REJECT
# [sunflower.vn]
DOMAIN-SUFFIX,ad.sunflower.vn,REJECT
DOMAIN-SUFFIX,sunflower.vn,REJECT
# [suno.vn]
DOMAIN-SUFFIX,kh.suno.vn,REJECT
# [surfcountor.com]
DOMAIN-SUFFIX,cdn.surfcountor.com,REJECT
DOMAIN-SUFFIX,cms.surfcountor.com,REJECT
DOMAIN-SUFFIX,surfcountor.com,REJECT
# [syphonseity.com]
DOMAIN-SUFFIX,syphonseity.com,REJECT
# [t2zc6vo8zj2ch6sh6kvu5vq8cjz4iv8v2aj1ckjy8zktaj8vm6visk6als8l.me]
DOMAIN-SUFFIX,t2zc6vo8zj2ch6sh6kvu5vq8cjz4iv8v2aj1ckjy8zktaj8vm6visk6als8l.me,REJECT
# [t7cp4fldl.com]
DOMAIN-SUFFIX,t7cp4fldl.com,REJECT
# [taboola.com]
DOMAIN-SUFFIX,taboola.com,REJECT
# [tapchimattran.vn]
DOMAIN-SUFFIX,log.tapchimattran.vn,REJECT
# [tapchitaichinh.vn]
DOMAIN-SUFFIX,log.tapchitaichinh.vn,REJECT
DOMAIN-SUFFIX,newlog.tapchitaichinh.vn,REJECT
# [tcdulichtphcm.vn]
DOMAIN-SUFFIX,thongke.tcdulichtphcm.vn,REJECT
# [tebrand.asia]
DOMAIN-SUFFIX,static.tebrand.asia,REJECT
DOMAIN-SUFFIX,tebrand.asia,REJECT
# [tebrand.vn]
DOMAIN-SUFFIX,static.tebrand.vn,REJECT
DOMAIN-SUFFIX,tebrand.vn,REJECT
# [teko.vn]
DOMAIN-SUFFIX,analytics.teko.vn,REJECT
DOMAIN-SUFFIX,monitor.teko.vn,REJECT
# [tekoapis.com]
DOMAIN-SUFFIX,tracking.tekoapis.com,REJECT
# [tenten.vn]
DOMAIN-SUFFIX,support.tenten.vn,REJECT
# [testcentre.vn]
DOMAIN-SUFFIX,k8s2.testcentre.vn,REJECT
DOMAIN-SUFFIX,testcentre.vn,REJECT
# [textlink.vn]
DOMAIN-SUFFIX,s6.textlink.vn,REJECT
# [tgdd.vn]
DOMAIN-SUFFIX,ma.tgdd.vn,REJECT
# [thadaco.vn]
DOMAIN-SUFFIX,banner.thadaco.vn,REJECT
# [thanhnien.vn]
DOMAIN-SUFFIX,ads.thanhnien.vn,REJECT
DOMAIN-SUFFIX,ai.thanhnien.vn,REJECT
DOMAIN-SUFFIX,fzip.thanhnien.vn,REJECT
DOMAIN-SUFFIX,log.thanhnien.vn,REJECT
DOMAIN-SUFFIX,quangcao.thanhnien.vn,REJECT
# [theleader.vn]
DOMAIN-SUFFIX,log.theleader.vn,REJECT
# [thesaigontimes.vn]
DOMAIN-SUFFIX,ads.thesaigontimes.vn,REJECT
DOMAIN-SUFFIX,cdn-ads.thesaigontimes.vn,REJECT
# [thethao247.vn]
DOMAIN-SUFFIX,staticad.thethao247.vn,REJECT
# [thethaovanhoa.vn]
DOMAIN-SUFFIX,logs.thethaovanhoa.vn,REJECT
DOMAIN-SUFFIX,thongke.thethaovanhoa.vn,REJECT
# [thichxemphim.net]
DOMAIN-SUFFIX,tracker.thichxemphim.net,REJECT
# [thitruongtaichinhtiente.vn]
DOMAIN-SUFFIX,ads.thitruongtaichinhtiente.vn,REJECT
# [thuanbui.me]
DOMAIN-SUFFIX,analytic.thuanbui.me,REJECT
# [thuonggiaonline.vn]
DOMAIN-SUFFIX,log.thuonggiaonline.vn,REJECT
# [thuvienphapluat.vn]
DOMAIN-SUFFIX,addlog.thuvienphapluat.vn,REJECT
DOMAIN-SUFFIX,adv.thuvienphapluat.vn,REJECT
# [thvli.vn]
DOMAIN-SUFFIX,ads.thvli.vn,REJECT
# [tienphong.vn]
DOMAIN-SUFFIX,log.tienphong.vn,REJECT
# [tieudungthoinay.vn]
DOMAIN-SUFFIX,log.tieudungthoinay.vn,REJECT
# [tiin.vn]
DOMAIN-SUFFIX,apiv2.tiin.vn,REJECT
# [tiki.vn]
DOMAIN-SUFFIX,ads.tiki.vn,REJECT
DOMAIN-SUFFIX,analytics.tiki.vn,REJECT
DOMAIN-SUFFIX,trackity.tiki.vn,REJECT
# [tiktok.com]
DOMAIN-SUFFIX,ads-api.tiktok.com,REJECT
DOMAIN-SUFFIX,ads-sg.tiktok.com,REJECT
DOMAIN-SUFFIX,ads.tiktok.com,REJECT
DOMAIN-SUFFIX,business-api.tiktok.com,REJECT
# [tinhte.vn]
DOMAIN-SUFFIX,affiliate.k4.tinhte.vn,REJECT
# [tinmoi24.vn]
DOMAIN-SUFFIX,r.tinmoi24.vn,REJECT
# [tinnhac.com]
DOMAIN-SUFFIX,log.tinnhac.com,REJECT
# [tinnhanhchungkhoan.vn]
DOMAIN-SUFFIX,interactive.tinnhanhchungkhoan.vn,REJECT
DOMAIN-SUFFIX,log.tinnhanhchungkhoan.vn,REJECT
# [tintuc.vn]
DOMAIN-SUFFIX,analytics.tintuc.vn,REJECT
# [tinxe.vn]
DOMAIN-SUFFIX,log.tinxe.vn,REJECT
DOMAIN-SUFFIX,tracking.tinxe.vn,REJECT
# [tjme.io]
DOMAIN-SUFFIX,api.tjme.io,REJECT
DOMAIN-SUFFIX,tjme.io,REJECT
DOMAIN-SUFFIX,txx.tjme.io,REJECT
DOMAIN-SUFFIX,web-api.tjme.io,REJECT
# [tkpopup.asia]
DOMAIN-SUFFIX,tkpopup.asia,REJECT
# [tkpopup.vn]
DOMAIN-SUFFIX,tkpopup.vn,REJECT
# [toathoule.com]
DOMAIN-SUFFIX,toathoule.com,REJECT
# [togataurnfuls.com]
DOMAIN-SUFFIX,togataurnfuls.com,REJECT
# [topdevvn.com]
DOMAIN-SUFFIX,tr.topdevvn.com,REJECT
# [toppage.vn]
DOMAIN-SUFFIX,toppage.vn,REJECT
# [toprework.vn]
DOMAIN-SUFFIX,ta.toprework.vn,REJECT
# [tpmedia.online]
DOMAIN-SUFFIX,cdn.tpmedia.online,REJECT
DOMAIN-SUFFIX,cdn1.tpmedia.online,REJECT
DOMAIN-SUFFIX,cdnv.tpmedia.online,REJECT
DOMAIN-SUFFIX,mvideo.tpmedia.online,REJECT
DOMAIN-SUFFIX,tpmedia.online,REJECT
DOMAIN-SUFFIX,www.tpmedia.online,REJECT
# [trangphim.net]
DOMAIN-SUFFIX,adserver.trangphim.net,REJECT
# [trangvangvietnam.com]
DOMAIN-SUFFIX,addtop.trangvangvietnam.com,REJECT
DOMAIN-SUFFIX,banner.trangvangvietnam.com,REJECT
# [trenddigital.vn]
DOMAIN-SUFFIX,trenddigital.vn,REJECT
# [trithuccuocsong.vn]
DOMAIN-SUFFIX,vietnamdaily-log.trithuccuocsong.vn,REJECT
# [tructiepbongda.me]
DOMAIN-SUFFIX,ttus.tructiepbongda.me,REJECT
# [trunkpkg.com]
DOMAIN-SUFFIX,trunkpkg.com,REJECT
# [truoctran.com]
DOMAIN-SUFFIX,truoctran.com,REJECT
# [tuoitre.vn]
DOMAIN-SUFFIX,quangcao.tuoitre.vn,REJECT
DOMAIN-SUFFIX,s.tuoitre.vn,REJECT
# [tuyensinh247.com]
DOMAIN-SUFFIX,adapi.tuyensinh247.com,REJECT
# [tv24.vn]
DOMAIN-SUFFIX,serving-ad.tv24.vn,REJECT
# [tv360.vn]
DOMAIN-SUFFIX,log.tv360.vn,REJECT
DOMAIN-SUFFIX,pubads-wiinvent.tv360.vn,REJECT
# [tvet-vietnam.org]
DOMAIN-SUFFIX,tracking.tvet-vietnam.org,REJECT
# [twitter.com]
DOMAIN-SUFFIX,ads-api.twitter.com,REJECT
DOMAIN-SUFFIX,ads-bidder-api.twitter.com,REJECT
DOMAIN-SUFFIX,ads.twitter.com,REJECT
# [u7z5fgj3k9c0vkah2v8zj1zj7v6gkm2f8zjc9j2vk6o9p2zks3a6sjc2mj6h.me]
DOMAIN-SUFFIX,u7z5fgj3k9c0vkah2v8zj1zj7v6gkm2f8zjc9j2vk6o9p2zks3a6sjc2mj6h.me,REJECT
# [ulinq.asia]
DOMAIN-SUFFIX,optimize.ulinq.asia,REJECT
# [ultraviewer.net]
DOMAIN-SUFFIX,ads.ultraviewer.net,REJECT
DOMAIN-SUFFIX,qc.ultraviewer.net,REJECT
# [ungdungtructuyen.vn]
DOMAIN-SUFFIX,analytics.ungdungtructuyen.vn,REJECT
# [unity3d.com]
DOMAIN-SUFFIX,iads.unity3d.com,REJECT
DOMAIN-SUFFIX,unityads.unity3d.com,REJECT
# [unpkg.com]
DOMAIN-SUFFIX,unpkg.com,REJECT
# [unsungpolicy.com]
DOMAIN-SUFFIX,unsungpolicy.com,REJECT
# [upremium.asia]
DOMAIN-SUFFIX,delivery.upremium.asia,REJECT
# [urekamedia.com]
DOMAIN-SUFFIX,optimize.urekamedia.com,REJECT
# [uto.vn]
DOMAIN-SUFFIX,banner.uto.vn,REJECT
# [v0h8c6kcd8wd9lzg2mtlo0gj7cju82latost2c8qjs2gj6yti8zhs5kltx7d.me]
DOMAIN-SUFFIX,v0h8c6kcd8wd9lzg2mtlo0gj7cju82latost2c8qjs2gj6yti8zhs5kltx7d.me,REJECT
# [v9banners.com]
DOMAIN-SUFFIX,v9banners.com,REJECT
DOMAIN-SUFFIX,www.v9banners.com,REJECT
# [vads.vn]
DOMAIN-SUFFIX,baogia.vads.vn,REJECT
DOMAIN-SUFFIX,vads.vn,REJECT
DOMAIN-SUFFIX,www.vads.vn,REJECT
# [vchat.vn]
DOMAIN-SUFFIX,core.vchat.vn,REJECT
# [vcmedia.vn]
DOMAIN-SUFFIX,adi.vcmedia.vn,REJECT
DOMAIN-SUFFIX,admicro1.vcmedia.vn,REJECT
DOMAIN-SUFFIX,admicro4.vcmedia.vn,REJECT
DOMAIN-SUFFIX,admicro5.vcmedia.vn,REJECT
DOMAIN-SUFFIX,admicro6.vcmedia.vn,REJECT
DOMAIN-SUFFIX,vcmedia.vn,REJECT
# [vegaid.vn]
DOMAIN-SUFFIX,tracking.vegaid.vn,REJECT
# [vepg.vn]
DOMAIN-SUFFIX,matomo.vepg.vn,REJECT
# [vhost.vn]
DOMAIN-SUFFIX,bi.vhost.vn,REJECT
# [viblo.asia]
DOMAIN-SUFFIX,analytics.viblo.asia,REJECT
# [vidcrunch.com]
DOMAIN-SUFFIX,vidcrunch.com,REJECT
# [videocloud.top]
DOMAIN-SUFFIX,analytics.videocloud.top,REJECT
# [vidoomy.com]
DOMAIN-SUFFIX,ads.vidoomy.com,REJECT
DOMAIN-SUFFIX,cpm.vidoomy.com,REJECT
DOMAIN-SUFFIX,pixel.vidoomy.com,REJECT
DOMAIN-SUFFIX,rtb-useast.vidoomy.com,REJECT
DOMAIN-SUFFIX,vidoomy.com,REJECT
DOMAIN-SUFFIX,www.vidoomy.com,REJECT
# [vidverto.io]
DOMAIN-SUFFIX,vidverto.io,REJECT
# [vieon.vn]
DOMAIN-SUFFIX,click.vieon.vn,REJECT
DOMAIN-SUFFIX,vieon-tracking.vieon.vn,REJECT
# [vietbao.vn]
DOMAIN-SUFFIX,ad.vietbao.vn,REJECT
DOMAIN-SUFFIX,ads.vietbao.vn,REJECT
DOMAIN-SUFFIX,tracking.vietbao.vn,REJECT
DOMAIN-SUFFIX,vietbao.vn,REJECT
# [vietbuzzad.com]
DOMAIN-SUFFIX,vietbuzzad.com,REJECT
DOMAIN-SUFFIX,www.vietbuzzad.com,REJECT
# [vietdorje.com]
DOMAIN-SUFFIX,vietdorje.com,REJECT
DOMAIN-SUFFIX,www.vietdorje.com,REJECT
# [vietid.net]
DOMAIN-SUFFIX,la.vietid.net,REJECT
# [vietlottsms.vn]
DOMAIN-SUFFIX,matomo.vietlottsms.vn,REJECT
# [vietnamfinance.vn]
DOMAIN-SUFFIX,analytics.vietnamfinance.vn,REJECT
# [vietnammoi.vn]
DOMAIN-SUFFIX,stats.vietnammoi.vn,REJECT
# [vietnamnet.vn]
DOMAIN-SUFFIX,track-srv.vietnamnet.vn,REJECT
# [vietnamnetad.vn]
DOMAIN-SUFFIX,img.vietnamnetad.vn,REJECT
DOMAIN-SUFFIX,log.vietnamnetad.vn,REJECT
DOMAIN-SUFFIX,rss2.vietnamnetad.vn,REJECT
DOMAIN-SUFFIX,tracking.vietnamnetad.vn,REJECT
DOMAIN-SUFFIX,vietnamnetad.vn,REJECT
DOMAIN-SUFFIX,widget.vietnamnetad.vn,REJECT
# [vietnamnetjsc.vn]
DOMAIN-SUFFIX,adclient.vietnamnetjsc.vn,REJECT
# [vietnamplus.vn]
DOMAIN-SUFFIX,en-log.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,es-log.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,fr-log.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,log.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,logen.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,loges.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,logfr.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,logru.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,logzh.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,ru-log.vietnamplus.vn,REJECT
DOMAIN-SUFFIX,vietnamplus.vn,REJECT
DOMAIN-SUFFIX,zh-log.vietnamplus.vn,REJECT
# [vietnhan.co]
DOMAIN-SUFFIX,traffic.vietnhan.co,REJECT
# [vietpub.com]
DOMAIN-SUFFIX,vietpub.com,REJECT
# [vietstock.vn]
DOMAIN-SUFFIX,ox1.vietstock.vn,REJECT
# [viettel.vn]
DOMAIN-SUFFIX,cdn1.vda.viettel.vn,REJECT
DOMAIN-SUFFIX,delivery.vda.viettel.vn,REJECT
DOMAIN-SUFFIX,log.vda.viettel.vn,REJECT
DOMAIN-SUFFIX,vda.viettel.vn,REJECT
DOMAIN-SUFFIX,vdacdn1.viettel.vn,REJECT
DOMAIN-SUFFIX,vdacdn2.viettel.vn,REJECT
# [viettimes.vn]
DOMAIN-SUFFIX,log.viettimes.vn,REJECT
# [viez.vn]
DOMAIN-SUFFIX,tracking.viez.vn,REJECT
# [violet.vn]
DOMAIN-SUFFIX,qc.violet.vn,REJECT
# [vipads.cc]
DOMAIN-SUFFIX,pv.vipads.cc,REJECT
DOMAIN-SUFFIX,vipads.cc,REJECT
DOMAIN-SUFFIX,www.vipads.cc,REJECT
# [vipads.live]
DOMAIN-SUFFIX,vipads.live,REJECT
DOMAIN-SUFFIX,www.vipads.live,REJECT
# [vishare.vn]
DOMAIN-SUFFIX,ads.vishare.vn,REJECT
# [vkool.net]
DOMAIN-SUFFIX,ad.vkool.net,REJECT
DOMAIN-SUFFIX,vkool.net,REJECT
# [vlr.vn]
DOMAIN-SUFFIX,ads.vlr.vn,REJECT
# [vmax.vn]
DOMAIN-SUFFIX,mautic.vmax.vn,REJECT
# [vnadssb.com]
DOMAIN-SUFFIX,vnadssb.com,REJECT
# [vnanet.vn]
DOMAIN-SUFFIX,analytic.vnanet.vn,REJECT
# [vnay.vn]
DOMAIN-SUFFIX,ad-admin.vnay.vn,REJECT
DOMAIN-SUFFIX,advert-admin.vnay.vn,REJECT
DOMAIN-SUFFIX,follow.vnay.vn,REJECT
DOMAIN-SUFFIX,log.vnay.vn,REJECT
DOMAIN-SUFFIX,report.vnay.vn,REJECT
DOMAIN-SUFFIX,shop.vnay.vn,REJECT
# [vnbusiness.vn]
DOMAIN-SUFFIX,la.vnbusiness.vn,REJECT
# [vnecdn.com]
DOMAIN-SUFFIX,core.vnecdn.com,REJECT
DOMAIN-SUFFIX,cpx.vnecdn.com,REJECT
DOMAIN-SUFFIX,dt.vnecdn.com,REJECT
DOMAIN-SUFFIX,go.vnecdn.com,REJECT
# [vnecdn.net]
DOMAIN-SUFFIX,adp.vnecdn.net,REJECT
DOMAIN-SUFFIX,la.vnecdn.net,REJECT
DOMAIN-SUFFIX,la2.vnecdn.net,REJECT
DOMAIN-SUFFIX,la3.vnecdn.net,REJECT
DOMAIN-SUFFIX,vnecdn.net,REJECT
# [vneconomy.vn]
DOMAIN-SUFFIX,log.vneconomy.vn,REJECT
DOMAIN-SUFFIX,tracker.vneconomy.vn,REJECT
# [vnexpress.net]
DOMAIN-SUFFIX,elogs.vnexpress.net,REJECT
DOMAIN-SUFFIX,logperf.vnexpress.net,REJECT
DOMAIN-SUFFIX,s-logperf.vnexpress.net,REJECT
DOMAIN-SUFFIX,tracking-amp.vnexpress.net,REJECT
# [vnfinance.vn]
DOMAIN-SUFFIX,log.vnfinance.vn,REJECT
# [vnncdn.net]
DOMAIN-SUFFIX,analytics.vnncdn.net,REJECT
DOMAIN-SUFFIX,tracking.vnncdn.net,REJECT
DOMAIN-SUFFIX,tracking2.vnncdn.net,REJECT
DOMAIN-SUFFIX,tracking3.vnncdn.net,REJECT
DOMAIN-SUFFIX,vnn-tracking.vnncdn.net,REJECT
# [vnnshop.vn]
DOMAIN-SUFFIX,adv.vnnshop.vn,REJECT
# [vnpgroup.net]
DOMAIN-SUFFIX,live.vnpgroup.net,REJECT
# [vnpt.vn]
DOMAIN-SUFFIX,analytics.vnpt.vn,REJECT
# [vnreview.vn]
DOMAIN-SUFFIX,analytics.vnreview.vn,REJECT
# [vov.vn]
DOMAIN-SUFFIX,log.vov.vn,REJECT
DOMAIN-SUFFIX,statistics-vov2.vov.vn,REJECT
DOMAIN-SUFFIX,statistics.vov.vn,REJECT
# [vov2.vn]
DOMAIN-SUFFIX,statistics.vov2.vn,REJECT
# [vovlive.vn]
DOMAIN-SUFFIX,ads.vovlive.vn,REJECT
# [vovworld.vn]
DOMAIN-SUFFIX,log.vovworld.vn,REJECT
# [vtc.vn]
DOMAIN-SUFFIX,ads.vtc.vn,REJECT
DOMAIN-SUFFIX,delivery.vtc.vn,REJECT
DOMAIN-SUFFIX,tracking.vtc.vn,REJECT
# [vtcnews.vn]
DOMAIN-SUFFIX,delivery.vtcnews.vn,REJECT
DOMAIN-SUFFIX,track.vtcnews.vn,REJECT
# [vtvdigital.vn]
DOMAIN-SUFFIX,a.vtvdigital.vn,REJECT
DOMAIN-SUFFIX,st-a.vtvdigital.vn,REJECT
# [vucar.vn]
DOMAIN-SUFFIX,plausible.vucar.vn,REJECT
# [wataads.com]
DOMAIN-SUFFIX,cdn.wataads.com,REJECT
DOMAIN-SUFFIX,wataads.com,REJECT
# [watanet.work]
DOMAIN-SUFFIX,d.watanet.work,REJECT
DOMAIN-SUFFIX,watanet.work,REJECT
# [webpush.vn]
DOMAIN-SUFFIX,webpush.vn,REJECT
# [webvb88.biz]
DOMAIN-SUFFIX,webvb88.biz,REJECT
# [weightypikas.shop]
DOMAIN-SUFFIX,weightypikas.shop,REJECT
# [wfgo5vjs6cp0cdjx7bms3cn9lof2p01xho0pxgm1fd2fah3j5d8qd7x1d6eu.me]
DOMAIN-SUFFIX,wfgo5vjs6cp0cdjx7bms3cn9lof2p01xho0pxgm1fd2fah3j5d8qd7x1d6eu.me,REJECT
# [wiinvent.tv]
DOMAIN-SUFFIX,api.wiinvent.tv,REJECT
DOMAIN-SUFFIX,cdn-embed.wiinvent.tv,REJECT
DOMAIN-SUFFIX,dev.embed.wiinvent.tv,REJECT
DOMAIN-SUFFIX,embed.wiinvent.tv,REJECT
DOMAIN-SUFFIX,games.wiinvent.tv,REJECT
DOMAIN-SUFFIX,pubads.wiinvent.tv,REJECT
DOMAIN-SUFFIX,static1.wiinvent.tv,REJECT
DOMAIN-SUFFIX,tv360-gametet.wiinvent.tv,REJECT
DOMAIN-SUFFIX,wiinvent.tv,REJECT
# [winigroup.vn]
DOMAIN-SUFFIX,track.winigroup.vn,REJECT
# [workers.dev]
DOMAIN-SUFFIX,app.sbz.workers.dev,REJECT
# [x-cdn.org]
DOMAIN-SUFFIX,x-cdn.org,REJECT
# [x.com]
DOMAIN-SUFFIX,ads-api.x.com,REJECT
# [xdn.vn]
DOMAIN-SUFFIX,s.baomoi.xdn.vn,REJECT
# [xedoisong.vn]
DOMAIN-SUFFIX,ads.xedoisong.vn,REJECT
# [xemphimso.com]
DOMAIN-SUFFIX,ads.xemphimso.com,REJECT
# [xemvtv.net]
DOMAIN-SUFFIX,adx.xemvtv.net,REJECT
DOMAIN-SUFFIX,an.xemvtv.net,REJECT
# [xtv.vn]
DOMAIN-SUFFIX,adx.xtv.vn,REJECT
# [y8z5nv0slz06vj2k5vh6akv7dj2c8aj62zhj2v7zj8vp0zq7fj2gf4mv6zsb.me]
DOMAIN-SUFFIX,y8z5nv0slz06vj2k5vh6akv7dj2c8aj62zhj2v7zj8vp0zq7fj2gf4mv6zsb.me,REJECT
# [yahoo.com]
DOMAIN-SUFFIX,ads.yahoo.com,REJECT
DOMAIN-SUFFIX,adserver.yahoo.com,REJECT
DOMAIN-SUFFIX,gemini.yahoo.com,REJECT
DOMAIN-SUFFIX,log.fc.yahoo.com,REJECT
DOMAIN-SUFFIX,partnerads.ysm.yahoo.com,REJECT
DOMAIN-SUFFIX,udcm.yahoo.com,REJECT
# [yahooinc.com]
DOMAIN-SUFFIX,adtech.yahooinc.com,REJECT
# [yandex.ru]
DOMAIN-SUFFIX,appmetrica.yandex.ru,REJECT
DOMAIN-SUFFIX,metrika.yandex.ru,REJECT
# [yeah1publishing.com]
DOMAIN-SUFFIX,mega1app.yeah1publishing.com,REJECT
DOMAIN-SUFFIX,www.yeah1publishing.com,REJECT
DOMAIN-SUFFIX,yeah1publishing.com,REJECT
# [yeuketqua.net]
DOMAIN-SUFFIX,yeuketqua.net,REJECT
# [yoads.net]
DOMAIN-SUFFIX,push.yoads.net,REJECT
DOMAIN-SUFFIX,push2.yoads.net,REJECT
DOMAIN-SUFFIX,www.yoads.net,REJECT
DOMAIN-SUFFIX,yoads.net,REJECT
# [yodimedia.com]
DOMAIN-SUFFIX,yodimedia.com,REJECT
# [yomedia.vn]
DOMAIN-SUFFIX,analytics.yomedia.vn,REJECT
DOMAIN-SUFFIX,delivery.yomedia.vn,REJECT
DOMAIN-SUFFIX,demo.yomedia.vn,REJECT
DOMAIN-SUFFIX,dmp-log.yomedia.vn,REJECT
DOMAIN-SUFFIX,media.yomedia.vn,REJECT
DOMAIN-SUFFIX,ss.yomedia.vn,REJECT
DOMAIN-SUFFIX,sslstatic.yomedia.vn,REJECT
DOMAIN-SUFFIX,static.yomedia.vn,REJECT
DOMAIN-SUFFIX,tracking.yomedia.vn,REJECT
DOMAIN-SUFFIX,yomedia.vn,REJECT
# [younetmedia.com]
DOMAIN-SUFFIX,digital.younetmedia.com,REJECT
DOMAIN-SUFFIX,facebookid.younetmedia.com,REJECT
DOMAIN-SUFFIX,gandalf.younetmedia.com,REJECT
DOMAIN-SUFFIX,git.younetmedia.com,REJECT
DOMAIN-SUFFIX,jenkins.younetmedia.com,REJECT
DOMAIN-SUFFIX,ranking.younetmedia.com,REJECT
DOMAIN-SUFFIX,sen02.younetmedia.com,REJECT
DOMAIN-SUFFIX,sh-cdn.younetmedia.com,REJECT
DOMAIN-SUFFIX,sh-staging-cdn.younetmedia.com,REJECT
DOMAIN-SUFFIX,sh-staging.younetmedia.com,REJECT
DOMAIN-SUFFIX,sh.younetmedia.com,REJECT
DOMAIN-SUFFIX,smtp1.younetmedia.com,REJECT
DOMAIN-SUFFIX,smtp2.younetmedia.com,REJECT
DOMAIN-SUFFIX,smtp3.younetmedia.com,REJECT
DOMAIN-SUFFIX,smtp4.younetmedia.com,REJECT
DOMAIN-SUFFIX,smtp5.younetmedia.com,REJECT
DOMAIN-SUFFIX,smtp6.younetmedia.com,REJECT
DOMAIN-SUFFIX,socialheat.younetmedia.com,REJECT
DOMAIN-SUFFIX,static.younetmedia.com,REJECT
DOMAIN-SUFFIX,www.younetmedia.com,REJECT
DOMAIN-SUFFIX,younetmedia.com,REJECT
# [z8g0wlq5p0f6jg3k7eh2kyd58hjeskx0w9g5eu7q3m5hyq8l0xwofj3ap2nv.me]
DOMAIN-SUFFIX,z8g0wlq5p0f6jg3k7eh2kyd58hjeskx0w9g5eu7q3m5hyq8l0xwofj3ap2nv.me,REJECT
# [zadn.vn]
DOMAIN-SUFFIX,adtima-common.zadn.vn,REJECT
DOMAIN-SUFFIX,adtima-media-td.zadn.vn,REJECT
DOMAIN-SUFFIX,adtima-media.zadn.vn,REJECT
DOMAIN-SUFFIX,adtima-static-td.zadn.vn,REJECT
DOMAIN-SUFFIX,adtima-static.zadn.vn,REJECT
DOMAIN-SUFFIX,adtima-video.zadn.vn,REJECT
DOMAIN-SUFFIX,api.sdk.zadn.vn,REJECT
DOMAIN-SUFFIX,log-anninhthudo.zadn.vn,REJECT
DOMAIN-SUFFIX,log-baobackan.zadn.vn,REJECT
DOMAIN-SUFFIX,log-baonghean.zadn.vn,REJECT
DOMAIN-SUFFIX,log-baophapluat.zadn.vn,REJECT
DOMAIN-SUFFIX,log-bizlive.zadn.vn,REJECT
DOMAIN-SUFFIX,log-giacngo.zadn.vn,REJECT
DOMAIN-SUFFIX,log-giaoduc.zadn.vn,REJECT
DOMAIN-SUFFIX,log-giaoducthoidai.zadn.vn,REJECT
DOMAIN-SUFFIX,log-kienthucnet.zadn.vn,REJECT
DOMAIN-SUFFIX,log-nhandan.zadn.vn,REJECT
DOMAIN-SUFFIX,log-plo.zadn.vn,REJECT
DOMAIN-SUFFIX,log-sggp.zadn.vn,REJECT
DOMAIN-SUFFIX,log-thanhnien.zadn.vn,REJECT
DOMAIN-SUFFIX,log-tienphong.zadn.vn,REJECT
DOMAIN-SUFFIX,log-tinnhanhchungkhoan.zadn.vn,REJECT
DOMAIN-SUFFIX,log-vietnamdaily.zadn.vn,REJECT
DOMAIN-SUFFIX,log-vovworld.zadn.vn,REJECT
DOMAIN-SUFFIX,log.sdk.zadn.vn,REJECT
DOMAIN-SUFFIX,mda.zadn.vn,REJECT
DOMAIN-SUFFIX,mplaylist-ads.zadn.vn,REJECT
DOMAIN-SUFFIX,zalo-ads-240-td.zadn.vn,REJECT
DOMAIN-SUFFIX,zalo-ads-240.zadn.vn,REJECT
DOMAIN-SUFFIX,zalo-ads-480-td.zadn.vn,REJECT
DOMAIN-SUFFIX,zalo-ads-480.zadn.vn,REJECT
DOMAIN-SUFFIX,zalo-ads-td.zadn.vn,REJECT
DOMAIN-SUFFIX,zalo-ads.zadn.vn,REJECT
# [zalo.ai]
DOMAIN-SUFFIX,stats.lab.zalo.ai,REJECT
# [zalo.me]
DOMAIN-SUFFIX,ads-platform.zalo.me,REJECT
DOMAIN-SUFFIX,ads.platform.zalo.me,REJECT
DOMAIN-SUFFIX,ads.zalo.me,REJECT
DOMAIN-SUFFIX,api.widget.zalo.me,REJECT
DOMAIN-SUFFIX,beta.ads.zalo.me,REJECT
DOMAIN-SUFFIX,button-call.zalo.me,REJECT
DOMAIN-SUFFIX,button-follow.zalo.me,REJECT
DOMAIN-SUFFIX,button-share.zalo.me,REJECT
DOMAIN-SUFFIX,groupstats.chat.zalo.me,REJECT
DOMAIN-SUFFIX,groupstats.event.zalo.me,REJECT
DOMAIN-SUFFIX,jr.ads.zalo.me,REJECT
DOMAIN-SUFFIX,jr.stg.ads.zalo.me,REJECT
DOMAIN-SUFFIX,m.ads.zalo.me,REJECT
DOMAIN-SUFFIX,page.widget.zalo.me,REJECT
DOMAIN-SUFFIX,preview.ads.zalo.me,REJECT
DOMAIN-SUFFIX,px.za.zalo.me,REJECT
DOMAIN-SUFFIX,stats.hc.score.dmp.zalo.me,REJECT
DOMAIN-SUFFIX,widget.chat.zalo.me,REJECT
# [zalo.video]
DOMAIN-SUFFIX,log.zalo.video,REJECT
# [zaloapp.com]
DOMAIN-SUFFIX,ads.zaloapp.com,REJECT
DOMAIN-SUFFIX,centralized.zaloapp.com,REJECT
DOMAIN-SUFFIX,jr.ads.zaloapp.com,REJECT
DOMAIN-SUFFIX,log.api.zaloapp.com,REJECT
DOMAIN-SUFFIX,media-ads.zaloapp.com,REJECT
DOMAIN-SUFFIX,photo-ads.zaloapp.com,REJECT
DOMAIN-SUFFIX,px.dmp.zaloapp.com,REJECT
DOMAIN-SUFFIX,px.za.zaloapp.com,REJECT
DOMAIN-SUFFIX,static-ads.zaloapp.com,REJECT
DOMAIN-SUFFIX,stats.dev.zaloapp.com,REJECT
DOMAIN-SUFFIX,stats.stg.zaloapp.com,REJECT
DOMAIN-SUFFIX,stats.zaloapp.com,REJECT
DOMAIN-SUFFIX,trk-pcweb.api.zaloapp.com,REJECT
DOMAIN-SUFFIX,wg.zaloapp.com,REJECT
DOMAIN-SUFFIX,zminer.zaloapp.com,REJECT
DOMAIN-SUFFIX,ztevents.zaloapp.com,REJECT
# [zamba.vn]
DOMAIN-SUFFIX,log.zamba.vn,REJECT
# [zapps.me]
DOMAIN-SUFFIX,analytics.zapps.me,REJECT
DOMAIN-SUFFIX,tech.zapps.me,REJECT
# [zapps.vn]
DOMAIN-SUFFIX,analytics.zapps.vn,REJECT
DOMAIN-SUFFIX,jslog.zapps.vn,REJECT
DOMAIN-SUFFIX,tracker-mw-zlivestream.zapps.vn,REJECT
DOMAIN-SUFFIX,tracker-zlivestream.zapps.vn,REJECT
DOMAIN-SUFFIX,tracking.api.media.zapps.vn,REJECT
DOMAIN-SUFFIX,za.zapps.vn,REJECT
DOMAIN-SUFFIX,zplayer.trk.zapps.vn,REJECT
# [zascdn.me]
DOMAIN-SUFFIX,ads.zascdn.me,REJECT
DOMAIN-SUFFIX,adtima-common.zascdn.me,REJECT
DOMAIN-SUFFIX,adtima-media.zascdn.me,REJECT
DOMAIN-SUFFIX,adtima-static.zascdn.me,REJECT
DOMAIN-SUFFIX,adtima-video.zascdn.me,REJECT
DOMAIN-SUFFIX,mplaylist-ads.zascdn.me,REJECT
# [zatomac.vn]
DOMAIN-SUFFIX,analytics.zatomac.vn,REJECT
# [zdn.vn]
DOMAIN-SUFFIX,240.zaloapp.ads.zdn.vn,REJECT
DOMAIN-SUFFIX,480.zaloapp.ads.zdn.vn,REJECT
DOMAIN-SUFFIX,adtima-static.aka.zdn.vn,REJECT
DOMAIN-SUFFIX,stc-support-app-brand.zdn.vn,REJECT
DOMAIN-SUFFIX,zaloads-480.zdn.vn,REJECT
DOMAIN-SUFFIX,zplayer-trk.zdn.vn,REJECT
# [zedcdn.me]
DOMAIN-SUFFIX,m.zedcdn.me,REJECT
DOMAIN-SUFFIX,me.zedcdn.me,REJECT
DOMAIN-SUFFIX,mme.zedcdn.me,REJECT
# [zigzag.vn]
DOMAIN-SUFFIX,zigzag.vn,REJECT
# [zim.vn]
DOMAIN-SUFFIX,analytics.zim.vn,REJECT
# [zing.vn]
DOMAIN-SUFFIX,ad.zing.vn,REJECT
DOMAIN-SUFFIX,adsbanner.game.zing.vn,REJECT
DOMAIN-SUFFIX,adstracking.apps.zing.vn,REJECT
DOMAIN-SUFFIX,adtima.brand.zing.vn,REJECT
DOMAIN-SUFFIX,adtimabot.brand.zing.vn,REJECT
DOMAIN-SUFFIX,adtimabox.brand.zing.vn,REJECT
DOMAIN-SUFFIX,app.brand.zing.vn,REJECT
DOMAIN-SUFFIX,banner.brand.zing.vn,REJECT
DOMAIN-SUFFIX,brand.zing.vn,REJECT
DOMAIN-SUFFIX,campaign.brand.zing.vn,REJECT
DOMAIN-SUFFIX,interactive.brand.zing.vn,REJECT
DOMAIN-SUFFIX,log.mp3.zing.vn,REJECT
DOMAIN-SUFFIX,log.news.zing.vn,REJECT
DOMAIN-SUFFIX,log.tv.zing.vn,REJECT
DOMAIN-SUFFIX,logv2.mp3.zing.vn,REJECT
DOMAIN-SUFFIX,stat.play.zing.vn,REJECT
DOMAIN-SUFFIX,stc.interactive.brand.zing.vn,REJECT
DOMAIN-SUFFIX,tracking.banner.g6.zing.vn,REJECT
DOMAIN-SUFFIX,tracking.playzing.g6.zing.vn,REJECT
DOMAIN-SUFFIX,tracking.tv.zing.vn,REJECT
DOMAIN-SUFFIX,zads.me.zing.vn,REJECT
DOMAIN-SUFFIX,zlog.mp3.zing.vn,REJECT
DOMAIN-SUFFIX,zt.me.zing.vn,REJECT
DOMAIN-SUFFIX,zt1.me.zing.vn,REJECT
# [zingmp3.vn]
DOMAIN-SUFFIX,log.zingmp3.vn,REJECT
DOMAIN-SUFFIX,za.zingmp3.vn,REJECT
DOMAIN-SUFFIX,zlog.zingmp3.vn,REJECT
# [zingnews.vn]
DOMAIN-SUFFIX,log.zingnews.vn,REJECT
# [zingplay.com]
DOMAIN-SUFFIX,trackingbr.zingplay.com,REJECT
DOMAIN-SUFFIX,trackingin.zingplay.com,REJECT
DOMAIN-SUFFIX,trackingsea.zingplay.com,REJECT
DOMAIN-SUFFIX,trackingvn.zingplay.com,REJECT
# [zinimedia.com]
DOMAIN-SUFFIX,ad.zinimedia.com,REJECT
DOMAIN-SUFFIX,zinimedia.com,REJECT
# [zmedia.vn]
DOMAIN-SUFFIX,server.zmedia.vn,REJECT
# [znews.vn]
DOMAIN-SUFFIX,log.znews.vn,REJECT
# [ztrck.me]
DOMAIN-SUFFIX,ztrck.me,REJECT
# [zunia.vn]
DOMAIN-SUFFIX,ads.zunia.vn,REJECT
DOMAIN-SUFFIX,zunia.vn,REJECT
# [zzcdn.me]
DOMAIN-SUFFIX,s.zzcdn.me,REJECT
# [zzz.vn]
DOMAIN-SUFFIX,s1.zzz.vn,REJECT