#!name=Locket Gold
#!desc=Gold
#!url=https://raw.githubusercontent.com/hoangsvn/hoangsvn/main/module/locketgold.module

[MITM]
hostname = %APPEND% api.revenuecat.com

[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),script-path=https://raw.githubusercontent.com/hoangsvn/hoangsvn/main/module/js/locket.js, requires-body=true, max-size=-1, timeout=60

[Header Rewrite]
^https?://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$) = delete header X-RevenueCat-ETag