#!name=Locket Gold
#!desc=Gold

[MITM]
hostname = %APPEND% api.revenuecat.com

[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),script-path=https://raw.githubusercontent.com/hoangsvn/hoangsvn/refs/heads/main/LocketGold/locket.js, requires-body=true, max-size=-1, timeout=60

[Header Rewrite]
^https?://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$) = delete header X-RevenueCat-ETag