#!url=https://raw.githubusercontent.com/hoangsvn/hoangsvn/main/module/soundcloud.module
#!name=SoundCloud
#!desc=Active Go++
#!date=8/21/2025, 1:45:11 AM

[MITM]
hostname= %APPEND% api-mobile.soundcloud.com

[Script]

SoundCloud=type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/hoangsvn/hoangsvn/main/extra/dist/soundcloud.js