#!url=https://raw.githubusercontent.com/hoangsvn/hoangsvn/main/module/soundcloud.module
#!name=SoundCloud Go++
#!desc=build:9/15/2025, 5:49:18 AM

[MITM]
hostname= %APPEND% api-mobile.soundcloud.com

[Script]

SoundCloud=type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/hoangsvn/hoangsvn/main/extra/dist/soundcloud.js