name: Build Module
on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Chọn module cần build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - youtube
          - spotify
          - soundcloud
          - adblock

jobs:
  build-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Npm install
        working-directory: extra
        run: npm install

      - name: Build Youtube
        if: ${{ github.event.inputs.module == 'all' || github.event.inputs.module == 'youtube' }}
        working-directory: extra
        run: npm run build:youtube

      - name: Build Spotify
        if: ${{ github.event.inputs.module == 'all' || github.event.inputs.module == 'spotify' }}
        working-directory: extra
        run: npm run build:spotify

      - name: Build SoundCloud
        if: ${{ github.event.inputs.module == 'all' || github.event.inputs.module == 'soundcloud' }}
        working-directory: extra
        run: npm run build:soundcloud

      - name: Build ADBlock
        if: ${{ github.event.inputs.module == 'all' || github.event.inputs.module == 'adblock' }}
        working-directory: extra
        run: npm run build:adblock

      - name: Config github User
        run: |
          git config user.name "${{ secrets.USER_NAME }}"
          git config user.email "${{ secrets.EMAIL }}"

      - name: Commit & Push
        run: |
          git add .
          git commit -m "Update Module by CICD Action"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
